Update google-ads-event-streaming.md
amplitude/amplitude-dev-center pull request #110
Opened 2023-12-04 15:08 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-12-11 19:37 UTC, markzegarelli requested changes

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +- This integration uses the [Upload Click Conversions API](https://developers.google.com/google-ads/api/docs/conversions/upload-clicks)).
```suggestion
- This integration uses Google's [Upload Click Conversions API](https://developers.google.com/google-ads/api/docs/conversions/upload-clicks)).
```

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +- A user property **Google Click ID (GLID** or **initial_gclid** is required in order for Amplitude to create a click conversion and pass that event to Google Ads. A Google Click ID (GCLID) is a para
```suggestion
- This integration requires a Google Click ID (`gclid` or `initial_gclid` to enable Amplitude to create the click conversion and pass that event to Google Ads. Google Ads relies on the `gclid` parameter to track user interactions with ads and attribute conversions back to specific ad clicks. When a user clicks an ad served through Google Ads, Google Ads generates a unique `gclid` value and appends it to the URL. This parameter identifies the click, and links it to subsequent conversions.
```

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +2. Enter your [**Google Ads Customer ID**](https://support.google.com/google-ads/answer/1704344?hl=en). A Google Ads Customer ID is a unique identifier assigned to each advertiser or business that us
```suggestion
2. Enter your [**Google Ads Customer ID**](https://support.google.com/google-ads/answer/1704344?hl=en). A Google Ads Customer ID is a unique identifier assigned to each advertiser or business that uses Google Ads. This ID helps Google track and manage accounts, campaigns, and billing information for advertisers.
```

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +3. Enter your [**Google Ads Conversion Action ID**](https://support.google.com/google-ads/thread/105330243?hl=en&sjid=5504033552721490234-EU). A Google Ads Conversion Action ID is a unique identifier
```suggestion
3. Enter your [**Google Ads Conversion Action ID**](https://support.google.com/google-ads/thread/105330243?hl=en&sjid=5504033552721490234-EU). This is a unique identifier associated with a specific conversion action in Google Ads, and represents a desired action that you want your visitors or users to take. For example, make a purchase, submit a contact form, or sign up for a newsletter.
```

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +4. Enter your [**Base64 encoded Google Cloud Service Account**](https://developers.google.com/google-ads/api/docs/oauth/service-accounts). A Google Cloud Service Account, also known as a Service Acco
```suggestion
4. Enter your [**Base64 encoded Google Cloud Service Account**](https://developers.google.com/google-ads/api/docs/oauth/service-accounts). A Google Cloud Service Account, also known as a Service Account, is a special type of Google account used for server-to-server interactions and authentication within Google Cloud Platform (GCP) services. It's can grant permissions and access to resources like Google Cloud Storage, Google Cloud Compute Engine, or other GCP services. Service Accounts have associated credentials (private keys or OAuth tokens) for authentication when you interact with GCP services programmatically.
```

2023-12-11 19:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +3. **Personalization:** By leveraging Amplitude's event data, you can create highly personalized ad campaigns. For example, you can use the data to target users who have completed specific actions on
```suggestion
3. **Personalization:** With Amplitude's event data, you can create highly personalized ad campaigns. For example, you can use the data to target users who have completed specific actions on your website or app with tailored ad messages or offers.
```

2023-12-11 21:33 UTC, Brandoncharleskhoo1 commented
Hi @markzegarelli , thanks for reviewing the document and suggesting those changes. I've implemented those suggested changes but I'm still unable to merge. Can you please help me to merge?

2023-12-12 17:54 UTC, markzegarelli approved these changes

2023-12-12 17:54 UTC, merged