Update index.md
amplitude/amplitude-dev-center pull request #115
Opened 2023-12-08 14:32 UTC by zheniasemenina

Added a note on Start/End Session events to clarify that they do count towards the event volume.

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-12-11 19:27 UTC, markzegarelli commented
@zheniasemenina I think we need to work on the whole paragraph that comes before your addition, as it's pretty confusing to me.

It starts by saying Amplitude sends events automatically, but in the next sentence says "even though these events aren't sent..."

Is it correct to say that Amplitude tracks `[Amplitude] Session Start` and `[Amplitude] Session End` by default, and these events count toward the allotted volume? If so, where does `session_id` come into play in this context?

Same issue in #114

2023-12-12 16:29 UTC, zheniasemenina commented
@markzegarelli 
> Is it correct to say that Amplitude tracks `[Amplitude] Session Start` and `[Amplitude] Session End` by default, and these events count toward the allotted volume? If so, where does `session_id` come into play in this context?

Right, we track `[Amplitude] Session Start` and `[Amplitude] Session End` by default, and these events count toward the allotted volume. 
We use `session_id` to distinguish between different sessions (all events with the same session_id are grouped together into the same session), and it comes into play because `[Amplitude] Session Start` generates a unique `session_id`  every time a new session starts (and `[Amplitude] Session End` means this session is over and it will be the last event with that same session number)

2023-12-12 18:09 UTC, markzegarelli commented
@zheniasemenina Cool! I think the context around this paragraph is mainly around how you can disable those defaults. 

How about something like this:

> By default, Amplitude sends `[Amplitude] Start Session` and `[Amplitude] End Session` events. These events count toward your contracted event volume. When you disable default session tracking, Amplitude no longer sends session start and end events, but continues to add `session_id` as an event property.

Is that correct regarding `session_id`?

2023-12-12 18:36 UTC, zheniasemenina commented
@markzegarelli  that's right!

2023-12-19 17:58 UTC, markzegarelli approved these changes

2024-01-02 16:51 UTC, markzegarelli requested changes

2024-01-02 16:51 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +By default, Amplitude sends `[Amplitude] Start Session` and `[Amplitude] End Session` events. These events count toward your contracted event volume. When you disable default session tracking, Amplit
```suggestion
By default, Amplitude sends `[Amplitude] Start Session` and `[Amplitude] End Session` events. These events count toward your contracted event volume. When you disable default session tracking, Amplitude no longer sends session start and end events, but continues to add session_id as an event property.
```

2024-01-02 22:28 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +By default, Amplitude sends `[Amplitude] Start Session` and `[Amplitude] End Session` events. These events count toward your contracted event volume. When you disable default session tracking, Amplit
```suggestion
By default, Amplitude sends `[Amplitude] Start Session` and `[Amplitude] End Session` events. These events count toward your contracted event volume. When you disable default session tracking, Amplitude no longer sends session start and end events, but continues to add `session_id` as an event property.
```

2024-01-02 22:28 UTC, markzegarelli approved these changes

2024-01-03 11:07 UTC, merged