add email as Braze event streaming identifier option
amplitude/amplitude-dev-center pull request #120
Opened 2023-12-15 18:01 UTC by sina-jamshidi

# Amplitude Developer Docs PR
Add Email as an identifier option for Braze event streaming and link to Braze documentation FAQ to point out some caveats

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-12-15 18:10 UTC, markzegarelli requested changes

2023-12-15 18:10 UTC, markzegarelli commented on docs/data/destinations/braze.md
> +    - [**Email**](https://www.braze.com/docs/api/endpoints/user_data/post_user_track/#frequently-asked-questions): Using email as the identifier without an External ID or Braze ID can lead to some un
```suggestion
    - [**Email**](https://www.braze.com/docs/api/endpoints/user_data/post_user_track/#frequently-asked-questions): Using email as the identifier without an External ID or Braze ID may lead to unexpected behavior. 
```

2023-12-15 18:12 UTC, sina-jamshidi commented on docs/data/destinations/braze.md
> +    - [**Email**](https://www.braze.com/docs/api/endpoints/user_data/post_user_track/#frequently-asked-questions): Using email as the identifier without an External ID or Braze ID can lead to some un
Ah good point thanks!

2023-12-16 00:17 UTC, markzegarelli approved these changes

2023-12-19 01:29 UTC, merged