Update destination-event-streaming-overview.md
amplitude/amplitude-dev-center pull request #129
Opened 2023-12-20 10:53 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-12-22 22:33 UTC, markzegarelli requested changes

2023-12-22 22:33 UTC, markzegarelli commented on docs/data/destination-event-streaming-overview.md
> +Event Streaming empowers you to share your Amplitude data seamlessly throughout your entire system. It allows you to utilize the valuable behavioral data in Amplitude to enhance customer profiles and
```suggestion
Event Streaming lets you share your Amplitude data throughout your entire system. Use the valuable behavioral data in Amplitude to enhance customer profiles and send data to your marketing, sales, and infrastructure tools.
```

@Brandoncharleskhoo1 What "sytstem" are you talking about here?

2023-12-22 22:33 UTC, markzegarelli commented on docs/data/destination-event-streaming-overview.md
> +With event streaming, you gain access to user-friendly, configuration-based tools that offer precise control over the data you transmit. You can filter data by user, group, and event properties, ensu
```suggestion
With event streaming, you gain access to user-friendly, configuration-based tools that offer precise control over the data you send. Filter data by user, group, and event properties, ensuring that you send only the relevant information to your downstream tools. Additionally, you can monitor key metrics like event volume, latency, and detailed delivery status to assess the performance and reliability of your streaming integration.
```

2023-12-22 22:33 UTC, markzegarelli commented on docs/data/destination-event-streaming-overview.md
> +- **Billing efficiency:** Amplitude tracks event volume based on distinct events sent. If the same event is sent to multiple Event Streaming destinations, it's counted only once for billing.
```suggestion
- **Billing efficiency:** Amplitude tracks event volume based on distinct events sent. If you send same event to multiple Event Streaming destinations, it's counted only once for billing.
```

2023-12-22 22:33 UTC, markzegarelli commented on docs/data/destination-event-streaming-overview.md
> +- **Retry mechanism:** Intermittent errors are addressed through in-memory retries with exponential backoff for initial sends. A robust retry pipeline attempts up to 10 times within a 4-hour window.
```suggestion
- **Retry mechanism:** Amplitude addresses Intermittent errors using in-memory retries with exponential backoff for initial sends. The retry pipeline attempts up to 10 times within a 4-hour window. This mechanism applies to all Event Streaming destinations.
```

2023-12-22 22:33 UTC, markzegarelli commented on docs/data/destination-event-streaming-overview.md
> +- **Streamlined monitoring and management:** The Event Streaming Debugger UI in Amplitude Data enables users to monitor pending retries, progress, and expired payloads. Insights into error categories
```suggestion
- **Streamlined monitoring and management:** The Event Streaming Debugger UI in Amplitude Data lets you monitor pending retries, progress, and expired payloads. Analyze failed payload samples to gain insight into error categories.
```

2024-02-13 06:44 UTC, Brandoncharleskhoo1 commented
Closing becauuse it has a conflict and I don't know how to resolve it. Created a new PR https://github.com/amplitude/amplitude-dev-center/pull/186

2024-02-13 06:44 UTC, closed without merging