Update optimizely-cohort.md
amplitude/amplitude-dev-center pull request #141
Opened 2024-01-09 23:34 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-01-10 21:53 UTC, markzegarelli requested changes

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +The Amplitude Behavioral Cohort Optimizely destination allows you to easily connect your Amplitude Cohorts to Optimizely Experimentation audiences (Web and Feature experimentation) and Optimizely CMS
```suggestion
The Amplitude Behavioral Cohort Optimizely destination  connects your Amplitude Cohorts to Optimizely Experimentation audiences (Web and Feature experimentation) and Optimizely CMS Visitor Groups. This allows you to target your cohorts with experiments and personalized website experiences leveraging your valuable Amplitude data. 
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +1. Within your Optimizely Data Platform environment navigate to the app directory via the ‘boxes and +’ icon in the top right.
```suggestion
1. in the Optimizely Data Platform environment navigate to the app directory.
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +2. Click on the **Amplitude** tile at the top and click the **Install** button in the top left.
```suggestion
2. Click the **Amplitude** tile at the top and click **Install** in the top left.
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +3. Once installed, click the **Settings** tab, click **Generate Token**, and copy the resulting token to your clipboard.
```suggestion
3. Once installed, navigate to the **Settings** tab, click **Generate Token**, and copy the resulting token to your clipboard.
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +5. Map the Amplitude **User ID** field to the Optimizely User ID field. Note the **User ID** you select must be the same **User ID** you’re targeting with experimentation and/or visitor groups.
```suggestion
5. Map the Amplitude **User ID** field to the Optimizely User ID field. The **User ID** you select must be the same **User ID** you target with experimentation and/or visitor groups. 
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +## Locating your cohort in Optimizely
```suggestion
## Locate your cohort in Optimizely
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +1. First, ensure your CMS Visitor Groups and/or Advanced Audience Targeting Experimentation integration(s) are configured. Here are relevant instructions for the one-time setup:
```suggestion
1. First, configure the relevant CMS Visitor Groups and/or Advanced Audience Targeting Experimentation integrations. See the one-time setup instructions below: 
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +2. Once you’ve completed the above you will find your Synced Amplitude Behavioral cohorts in the CMS Visitor Groups UI as well as the Experimentation Audience Builder. See below
```suggestion
2. Once you’ve completed the above, find the Synced Amplitude Behavioral cohorts in the CMS Visitor Groups UI and the Experimentation Audience Builder.
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +![screenshot of the new SFDC group mapping](../../assets/images/OPTIMIZELY-Experimentation-Audience-Builder.png)
```suggestion
```

2024-01-10 21:53 UTC, markzegarelli commented on docs/data/destinations/optimizely-cohort.md
> +![screenshot of the new SFDC group mapping](../../assets/images/OPTIMIZELY-CMS-Visitor-Groups-UI.png)
```suggestion
```
As I mentioned, we don't want to include screenshots from other tools, since these can change and cause more confusion for the user.

2024-02-08 02:09 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/optimizely-cohort.md
> +![screenshot of the new SFDC group mapping](../../assets/images/OPTIMIZELY-CMS-Visitor-Groups-UI.png)
OKies makes sense! Thank you

2024-02-08 02:21 UTC, Brandoncharleskhoo1 reviewed
Updated the developer docs as the Senior PM from OPtimizely reached out

2024-02-08 17:02 UTC, markzegarelli approved these changes

2024-02-13 06:29 UTC, merged