Update Braze, Intercom, Iterable, and Customer.io user fowarding to reflect new changes to the feature
amplitude/amplitude-dev-center pull request #154
Opened 2024-01-23 03:17 UTC by sina-jamshidi

# Amplitude Developer Docs PR

## Description

This feature has been updated to be "user update forwarding". We will now forward any user creation and property updates based the user's property selections. 
We are also re-enabling Braze user update forwarding as it had been disabled while waiting for this feature

## Deadline

When do these changes need to be live on the site?

In coordination with the UI release of this feature for Braze

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-01-23 17:33 UTC, markzegarelli requested changes

2024-01-23 21:43 UTC, sina-jamshidi commented on docs/data/destinations/braze.md
> +Under **Send Users**, make sure the toggle is enabled ("Users updates are sent to Braze") if you want to stream user and property updates to Braze. When enabled, users are automatically created or up
Just going to edit these suggestions a bit as they're slightly inaccurate. The setting itself is called "Send Users". 
`("Users updates are sent to Braze")` is the subtitle when the setting is enabled so I think we were trying to drive that home.

How's this?

> To stream user and property updates to Braze, enable **Send Users**. This setting creates or updates users in Braze when you update them in Amplitude with the [HTTP V2 API](/analytics/apis/http-v2-api/) or [Identify API](/analytics/apis/identify-api/). This integration doesn't support scheduled or on-demand updates.

2024-01-23 21:53 UTC, sina-jamshidi commented on docs/data/destinations/customerio.md
> +(optional) In **Select additional properties**, select any user properties you want to send to Customer.io. If you don't select any properties here, Amplitude doesn't send any. Whenever these propert
We want to communicate 3 points with this:
1. We will send updates only when the selected properties are updated (eg. if you select them, but they're never updated for a user, we're not going to send anything)
2. We will only send the selected properties
3. If no properties are selected, we still send the user (eg. with a user id), but no additional properties

How's this?
> You can optionally select user properties to send to Customer.io in the **Select additional properties** field. Amplitude sends only the properties you select and only when they are updated. Amplitude sends these properties as [Customer.io user attributes](https://www.customer.io/docs/attributes/). This integration doesn't support transformed user properties.

2024-01-25 17:03 UTC, markzegarelli approved these changes

2024-01-26 05:48 UTC, merged