Sky 4308 add versions endpoint
amplitude/amplitude-dev-center pull request #163
Opened 2024-01-30 05:38 UTC by zhukaihan

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-01-30 23:25 UTC, markzegarelli requested changes

2024-01-30 23:25 UTC, markzegarelli commented on docs/experiment/apis/management-api/versions.md
> +Versions will be ordered by version creation time descending.
```suggestion
Versions are ordered by version creation time descending.
```

2024-01-30 23:25 UTC, markzegarelli commented on docs/experiment/apis/management-api/versions.md
> +| <div class="big-column">Name</div> | Description |
Recommend removing this table, if there is only one row / section.

2024-01-31 01:34 UTC, bgiori approved these changes

2024-01-31 23:12 UTC, markzegarelli commented on docs/experiment/apis/management-api/versions.md
> +------
```suggestion
```

2024-01-31 23:12 UTC, markzegarelli approved these changes

2024-02-05 17:50 UTC, merged