AMP-92753 Add Snowflake Data Share setup steps and limitation
amplitude/amplitude-dev-center pull request #166
Opened 2024-01-30 18:41 UTC by joez2

# Amplitude Developer Docs PR

## Description

Add Snowflake Data Share setup steps and limitation sections.

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-01-30 23:10 UTC, markzegarelli requested changes

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +4. Click **Next**, enter the name of this Snowflake export and click Finish.
```suggestion
5. Click **Next**, enter the name of this Snowflake export and click Finish.
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +## Set up a recurring data export to Snowflake via Data Share
```suggestion
## Set up a recurring data export to Snowflake with Data Share
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +Creating a recurring data export is a simple process you can handle yourself.
```suggestion
Data Share enables you to create a recurring data export and monitor existing export jobs.
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +This method also lets you watch jobs.
```suggestion
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +4. Choose which data you'd like to include in this export: *Raw events every 5 minutes*, *Merged IDs every hour*, or export both.
```suggestion
4. Choose which data to include in this export: *Raw events every 5 minutes*, *Merged IDs every hour*, or both.
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +All future events are automatically sent to your Snowflake via Data Share.
```suggestion
When complete, Amplitude sends all future events to Snowflake with Data Share.
```

2024-01-30 23:10 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +From here, Amplitude generates micro-batch files at five-minute intervals and loads them to Amplitude's Snowflake account every 5 minutes, then data share with customer's Snowflake account.
@joez2 
This sentence is a a little confusing. I think we can combine with the sentence above. Does micro-batch file creation _and_ transmission to Amplitude's Snowflake instance happen every 5 minutes? What about if they choose *Merged IDs every hour*?

2024-01-30 23:49 UTC, joez2 commented on docs/data/destinations/snowflake-data-share.md
> +Creating a recurring data export is a simple process you can handle yourself.
This will be the same as a normal Snowflake export, except once exported to Amplitude's Snowflake, it will data share with the customer to give them the access, so I think the original statement is more clear.

2024-01-30 23:49 UTC, joez2 commented on docs/data/destinations/snowflake-data-share.md
> +From here, Amplitude generates micro-batch files at five-minute intervals and loads them to Amplitude's Snowflake account every 5 minutes, then data share with customer's Snowflake account.
Here we only talk about raw events. Maybe we can simply remove this, given we have already mentioned: 
*Raw events every 5 minutes*, *Merged IDs every hour* above

2024-01-30 23:59 UTC, markzegarelli commented on docs/data/destinations/snowflake-data-share.md
> +Creating a recurring data export is a simple process you can handle yourself.
Cool, just wanted to get away from saying "simple process you can handle yourself", as it skews a bit toward marketing.

2024-01-31 00:05 UTC, joez2 commented on docs/data/destinations/snowflake-data-share.md
> +Creating a recurring data export is a simple process you can handle yourself.
Totally make sense, I have just removed this completely. Please review. Thanks!

2024-01-31 00:05 UTC, joez2 commented on docs/data/destinations/snowflake-data-share.md
> +From here, Amplitude generates micro-batch files at five-minute intervals and loads them to Amplitude's Snowflake account every 5 minutes, then data share with customer's Snowflake account.
Removed :)

2024-01-31 00:08 UTC, markzegarelli approved these changes

2024-01-31 00:08 UTC, markzegarelli commented
@joez2 LGTM!

2024-01-31 00:13 UTC, merged