Create Azure Blob Storage export documentation
amplitude/amplitude-dev-center pull request #171
Opened 2024-02-02 17:54 UTC by LeontiBrechko

# Amplitude Developer Docs PR

## Description

Adds Azure Blob Storage export documentation

## Deadline

Feb 16, 2024

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [x] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-02-02 18:35 UTC, markzegarelli requested changes

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Amplitude users can now export Amplitude event data and merged user data to their Azure Blob Storage container. Azure Blob Storage's container policies allow you to manage and programmatically export
```suggestion
Amplitude's Azure Blob Storage destination enables you to export Amplitude event data and merged user data to your Azure Blob Storage container. You can use Azure Blob Storage's container policies to manage and export this data programmatically into an Azure container. Amplitude allows recurring syncs as often as once per hour.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Before you can export data from Amplitude to Azure Blob Storage, there are several prerequisites that need to be met in your Azure environment.
```suggestion
Before you can export data from Amplitude to Azure Blob Storage, ensure your Azure environment meets the following prerequisites:
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +    Create a service principal in Azure for Amplitude to use when accessing your Blob Storage. Take note of the `tenantId`, `clientId`, and `clientSecret`, as these will be needed for setting up the
```suggestion
    Create a service principal in Azure for Amplitude to use to access your Blob Storage. Copy the `tenantId`, `clientId`, and `clientSecret`, Amplitude requires these details to set up the connection with Azure. Follow this guide to create a service principal:
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +        Read permissions required for ensuring data exported only once during recurring export. Delete permissions required for deduplication during manual export (a.k.a. backfill export).
@LeontiBrechko I don't quite follow this note. Is this accurate?

Azure requires `read` permissions to ensure data isn't exported more than once for recurring exports. 
Azure requires  `delete` permissions to enable deduplication during a manual export, for example when you export backfill data.

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Completing these steps ensures that your Azure environment is properly configured and ready to securely receive data exports from Amplitude.
```suggestion
Once complete, these steps ensure your Azure environment is ready to receive secure data exports from Amplitude.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +To export your Amplitude data to Azure Blob Storage, follow these steps:
```suggestion
To export your Amplitude data to Azure Blob Storage:
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +3. On the **Getting Started** tab, select the data you'd like to export. Options include *Export events ingested today and moving forward*, *Export all merged Amplitude IDs*, or both.
```suggestion
3. On the **Getting Started** tab, select the data to export. Options include *Export events ingested today and moving forward*, *Export all merged Amplitude IDs*, or both.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +        You can export these two different data types to separate containers, if you prefer. You'll just need to complete the setup flow twice: once for each data type.
@LeontiBrechko 
Does each data type / container require a separate instance of the destination?

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +6. After entering the credentials, fill out the Azure Blob Storage container details in the *Azure Blob Storage Container Details* section.
```suggestion
6. Complete the Azure Blob Storage container details in the *Azure Blob Storage Container Details* section. Click **Next**.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +7. Click **Next**. Amplitude attempts a test upload to check that the entered credentials work. If the upload is successful, click **Finish** to complete the Azure Blob Storage destination configurat
```suggestion
7. Amplitude attempts a test upload to check that the entered credentials work. If the upload is successful, click **Finish** to complete the Azure Blob Storage destination configuration and activation.
```

If the test upload isn't successful, how detailed are the error messages? Should we include troubleshooting information here?

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +All future events/merged users are automatically sent to your Azure Blob Storage. Amplitude exports files to your Azure account every hour.
```suggestion
When complete, Amplitude sends all future events/merged users to your Azure Blob Storage once per hour.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +You can backfill historical data to Azure Blob Storage by manually exporting data.
```suggestion
Complete a manual export to backfill and send historical data to Azure Blob Storage.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +1. Go to the Azure Blob Storage export connection page created in the section above.
```suggestion
1. Open the instance of the Azure Blob Storage destination you created above. Navigate to the Export Connection page.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +3. Select the desired date range.
```suggestion
3. Select the date range to export.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +If the backfill range overlaps with the range of previously exported data, Amplitude will de-duplicate overlapping data.
```suggestion
If the backfill range overlaps with the range of previously exported data, Amplitude de-duplicates any overlapping data.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Data is exported hourly as zipped archive JSON files, and partitioned by the hour with one or multiple files per hour. Each file contains one event JSON object per line.
```suggestion
Amplitude exports data hourly as a zipped archive of JSON files, partitioned by the hour with one or more files per hour. Each file contains one event JSON object per line.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Here is the exported data JSON object schema:
```suggestion
The exported data JSON object schema is:
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Data is exported hourly as zipped archive JSON files. Each file contains one merged Amplitude ID JSON object per line.
```suggestion
Amplitude exports data as a zipped archive of JSON files. Each file contains one merged Amplitude ID JSON object per line.
```

2024-02-02 18:35 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +Merged ID JSON objects have the following schema:
```suggestion
The exported data JSON object schema is:
```

2024-02-05 19:31 UTC, LeontiBrechko commented on docs/data/destinations/azure-blob-storage.md
> +        Read permissions required for ensuring data exported only once during recurring export. Delete permissions required for deduplication during manual export (a.k.a. backfill export).
~~Azure~~ Amplitude requires read permissions to ensure data isn't exported more than once for recurring exports.
~~Azure~~ Amplitude requires delete permissions to enable deduplication during a manual export, for example when you export backfill data.

2024-02-06 17:31 UTC, markzegarelli commented on docs/data/destinations/azure-blob-storage.md
> +        Read permissions required for ensuring data exported only once during recurring export. Delete permissions required for deduplication during manual export (a.k.a. backfill export).
```suggestion
        Amplitude requires the following permissions in Azure:
        - `read` to ensure data isn't exported more than once for recurring exports.
        - `delete` to enable deduplication during a manual export, for example when you export backfill data.
```

2024-02-06 17:53 UTC, markzegarelli approved these changes

2024-02-07 17:03 UTC, LeontiBrechko commented
@markzegarelli thanks a lot for your input! 

Just a not for myself: we need to add the Azure link to this page as well: https://pr-171.d19s7xzcva2mw3.amplifyapp.com/data/destination-cloud-storage-overview/

2024-02-07 20:45 UTC, markzegarelli commented
> https://pr-171.d19s7xzcva2mw3.amplifyapp.com/data/destination-cloud-storage-overview/

@LeontiBrechko I added the icon and updated the page, but I'm not sure if it's the right logo. Please let me know once the preview build completes.

2024-02-20 18:31 UTC, merged