Update Experiment PHP SDK with AssignmentTrackingProvider docs
amplitude/amplitude-dev-center pull request #199
Opened 2024-02-15 21:22 UTC by tyiuhc

# Amplitude Developer Docs PR

## Description

Update Experiment PHP SDK with AssignmentTrackingProvider docs

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-02-16 18:19 UTC, markzegarelli requested changes

2024-02-16 18:19 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +The default assignment tracking provider is a basic implementation of the interface which uses the synchronous internal `Amplitude` package. It is only recommended for use of testing and applications
It might be worth adding some more context around the difference between  `AssignmentTrackingProvider` and `DefaultAssignmentTrackingProvider`. 

Why do we recommend the default only for testing and applications where latency isn't as much of a concern? Why is there increased latency?

2024-02-16 18:41 UTC, tyiuhc commented on docs/experiment/sdks/php-sdk.md
> +`track()` is called by the local evaluation client when an assignment event needs to be tracked, which happens when [`evaluate()`](#evaluate) is used. The implementation of `track()` should eventuall
Ah my wording was unclear here. `evaluate()` will always create an assignment event, which will be sent via `track()` (after deduplication within the SDK).

2024-02-16 18:45 UTC, tyiuhc commented on docs/experiment/sdks/php-sdk.md
> +The default assignment tracking provider is a basic implementation of the interface which uses the synchronous internal `Amplitude` package. It is only recommended for use of testing and applications
This is because the `DefaultAssignmentTrackingProvider` is implemented to send blocking, synchronous HTTP requests directly to Amplitude, which takes time to resolve. A custom `AssignmentTrackingProvider` implementation can take strategies to mitigate this (e.g. sending assignment events to another service which processes them async).

2024-02-16 19:01 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +`track()` is called by the local evaluation client when an assignment event needs to be tracked, which happens when [`evaluate()`](#evaluate) is used. The implementation of `track()` should eventuall
Got it. Just want to make sure we're providing the right context with the code sample.

The code sample demonstrates calling `track()`, and there's an assignment variable there. Is that variable the output of a previous `evaluate()` call?

If so, does this make sense?

> The local evaluation client calls `track()` on any untracked assignments that result from a previous evaluation. After deduplication in the SDK, `track()` sends the event to Analytics.

2024-02-16 21:48 UTC, tyiuhc commented on docs/experiment/sdks/php-sdk.md
> +`track()` is called by the local evaluation client when an assignment event needs to be tracked, which happens when [`evaluate()`](#evaluate) is used. The implementation of `track()` should eventuall
So within the `evaluate()` call, if assignment tracking has been set up, all evaluations will result in an assignment event being created, we then check it against the assignment cache to see if the same assignment has been sent recently, if not, `track()` is automatically called.

2024-02-16 23:56 UTC, markzegarelli requested changes

2024-02-16 23:56 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +The local evaluation client uses an assignment tracking provider to send assignment events to Amplitude. While a default assignment tracking provider is provided for the use of testing, due to its sy
```suggestion
The local evaluation client uses an assignment tracking provider to send assignment events to Amplitude. Amplitude provides a default assignment tracking provider, but this is best used for testing due to its synchronous nature. Amplitude recommends that you use a custom provider for increased flexibility and performance.
```

2024-02-16 23:56 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +The default assignment tracking provider is a basic implementation of the interface which uses the internal `Amplitude` package to send assignment events via synchronous HTTP requests.
```suggestion
The default assignment tracking provider is a basic implementation of the interface which uses the internal `Amplitude` package to send assignment events through synchronous HTTP requests.
```

2024-02-16 23:56 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +`track()` is called by the local evaluation client when an assignment event needs to be tracked, which happens when [`evaluate()`](#evaluate) is used. The implementation of `track()` should eventuall
```suggestion
The local evaluation client calls `track()` when it determines there are untracked assignment events. It compares the resulting assignment from `evaluate()` with the assignment cache and tracks it if it's not in the cache.
```

Not trying to be nitpicky about this, just want to try to make it as clear as possible.

2024-02-17 00:04 UTC, tyiuhc commented on docs/experiment/sdks/php-sdk.md
> +`track()` is called by the local evaluation client when an assignment event needs to be tracked, which happens when [`evaluate()`](#evaluate) is used. The implementation of `track()` should eventuall
Not at all, thanks for the help! I think this is much clearer.

2024-02-17 00:34 UTC, markzegarelli approved these changes

2024-02-17 00:35 UTC, merged