Update Experiment docs for default deployment
amplitude/amplitude-dev-center pull request #203
Opened 2024-02-20 21:48 UTC by tyiuhc

# Amplitude Developer Docs PR

## Description

Update Experiment docs for default deployment

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-02-23 20:39 UTC, bgiori approved these changes
Hold off on any merge until we release the feature

2024-04-05 21:55 UTC, markzegarelli requested changes

2024-04-05 21:55 UTC, markzegarelli commented on docs/experiment/general/data-model.md
> +    Deployments are either client or server deployments. Client-side deployments should be used to initialize client-side SDKs, and server-side deployments should be used to initialize server-side SD
```suggestion
    Deployments are either client or server deployments. Use client-side deployments should to initialize client-side SDKs, and server-side deployments to initialize server-side SDKs or authorize requests to the Evaluation API.
```

2024-04-05 21:55 UTC, markzegarelli commented on docs/experiment/general/data-model.md
> +Deployments live within Amplitude Analytics projects, and a project can have multiple deployments. Deployments are generally named after the platform (client-side) or service (server-side) which vari
```suggestion
Deployments belong to Amplitude Analytics projects, and a project can have multiple deployments. Amplitude recommends that you name deployments after the platform (client-side) or service (server-side) to which Experiment serves variants (for example: `android`, `ios`, `web`). The default project API key deployment is useful for getting started, but using explicit deployments for each platform or service is the best practice for larger organizations or teams that may share the same Amplitude project across multiple platforms for the same application.
```

2024-04-05 21:55 UTC, markzegarelli commented on docs/experiment/guides/getting-started/index.md
> +1. [Create a flag](./create-a-flag.md), and add a [deployment](../../general/data-model.md#deployments). Flags alone are used for standard feature flagging without user analysis. Experiments are used
```suggestion
1. [Create a flag](./create-a-flag.md), and add a [deployment](../../general/data-model.md#deployments). Use flags by themselves for standard feature flagging without user analysis. Use experiments for feature experimentation on users. Learn more about [flags and experiments](../../general/data-model/#flags-and-experiments).
```

2024-04-05 21:59 UTC, bgiori commented on docs/experiment/general/data-model.md
> +    Deployments are either client or server deployments. Client-side deployments should be used to initialize client-side SDKs, and server-side deployments should be used to initialize server-side SD
```suggestion
    Deployments are either client or server deployments. Use client-side deployments to initialize client-side SDKs, and server-side deployments to initialize server-side SDKs or authorize requests to the Evaluation API.
```

2024-04-05 21:59 UTC, bgiori commented on docs/experiment/guides/getting-started/index.md
> +1. [Create a flag](./create-a-flag.md), and add a [deployment](../../general/data-model.md#deployments). Flags alone are used for standard feature flagging without user analysis. Experiments are used
```suggestion
1. [Create a flag](./create-a-flag.md), and add a [deployment](../../general/data-model.md#deployments). Use flags for standard feature flagging without user analysis. Use experiments for feature experimentation on users. Learn more about [flags and experiments](../../general/data-model/#flags-and-experiments).
```

2024-04-06 00:03 UTC, markzegarelli approved these changes

2024-04-08 19:23 UTC, merged