Add Flutter SDK migration guide
amplitude/amplitude-dev-center pull request #239
Opened 2024-03-12 22:00 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

Add migration guide for the new Flutter SDK 4.0.

## Deadline

Do **NOT** merge this until the beta version is released at https://github.com/amplitude/Amplitude-Flutter/pull/179

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [x] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-03-12 22:15 UTC, Mercy811 commented
Hi @markzegarelli, yes, I will have another PR for the full reference of Flutter v4 in this week. Any concern if I merge this one first?

2024-03-12 22:22 UTC, markzegarelli commented
@Mercy811 No concern. Will version we move version 3 to maintenance? If so, I'd prefer to hold off on adding it to the nav, since we've traditionally sat the migration guides next to the doc for the previous version of the SDK.

2024-03-12 22:41 UTC, markzegarelli requested changes

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +Amplitude Flutter SDK 4.0 features default event tracking, simplified interfaces and wraps on the latest [Amplitude iOS SDK](/data/sdks/ios-swift/) and [Android Kotlin SDK](/data/sdks/android-kotlin/
```suggestion
Amplitude Flutter SDK 4.0 features default event tracking, simplified interfaces, and wraps the latest [Amplitude iOS](/data/sdks/ios-swift/) and [Android Kotlin](/data/sdks/android-kotlin/) SDKs. 
```

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +Go to the pubspec.yaml file and update the dependency.
```suggestion
Open `pubspec.yaml` and update the dependency:
```

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +Flutter SDK 4.0 offers an API to instrument events. To migrate to the Flutter SDK 4.0, you need to update a few calls. The following sections detail which calls have changed.
```suggestion
Flutter SDK 4.0 offers an API to instrument events. To migrate to Flutter SDK 4.0, you need to update a few calls. The following sections detail which calls have changed.
```

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +Like all other calls, `instance()` has been removed. Configuration is handled differently. The Flutter SDK 4.0 use the Configuration object to set the configuration. See [Configuration](#configuratio
```suggestion
Like all other calls, `instance()` is removed. Flutter SDK 4.0 uses the Configuration object to set the configuration. See [Configuration](#configuration) for more information.
```

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +The configurations for the new SDK are simpler and more consistent across runtimes. Some configurations are no longer supported. The Flutter SDK 3.0 uses setters for configuration. The configuration
```suggestion
Flutter SDK 4.0 includes the following configuration changes:

- It's more consistent across runtimes.
- It no longer supports certain configurations.
- It uses an instance variable for configuration, versus setters in SDK version 3.0.
- Configuration is immutable after you pass it to Amplitude.
```

2024-03-12 22:41 UTC, markzegarelli commented on docs/data/sdks/flutter/migration.md
> +The Flutter SDK 3.0 offered a variety of `logEvent` APIs with `withEventProperties`, `withApiProperties`, `withUserProperties`, `withGroup`, `withGroupProperties`, `withTimestamp`, `outOfSession`, to
```suggestion
Flutter SDK 4.0 uses a unified `track` API to replace the following `logEvent` API variations:

- `withEventProperties`
- `withApiProperties`
- `withUserProperties`
- `withGroup`
- `withGroupProperties`
```

Changed the order of reference here and made it a list.

2024-03-12 22:41 UTC, markzegarelli commented on mkdocs.yml
> +        - data/sdks/flutter/migration.md
```suggestion
       # - data/sdks/flutter/migration.md
```

Would like to hold off on listing this until the new version 4.0 doc is ready.

2024-03-13 18:12 UTC, Mercy811 commented on mkdocs.yml
> +        - data/sdks/flutter/migration.md
Makes sense! Even though it's not visible on nav bar, customers can still access it by url. Update it at https://github.com/amplitude/amplitude-dev-center/pull/239/commits/57333993c74bc034be1119c45fb4673deaaae36b

2024-03-13 18:45 UTC, markzegarelli approved these changes

2024-03-14 16:23 UTC, justin-fiedler commented on docs/data/sdks/flutter/migration.md
> ++ amplitude.track(event: BaseEvent(eventType:'BUTTON_CLICKED'))
nit: this usage seems verbose. If we always need to pass an event, can we make the parameter unnamed?

`amplitude.track(BaseEvent(eventType:'BUTTON_CLICKED'))`

2024-03-14 17:57 UTC, Mercy811 commented on docs/data/sdks/flutter/migration.md
> ++ amplitude.track(event: BaseEvent(eventType:'BUTTON_CLICKED'))
I noticed that two after the release. I've put it to the backlog and will update it in the next beta version. https://amplitude.atlassian.net/wiki/spaces/GOV/pages/2255355925/Flutter+SDK+update+to+wrap+on+the+latest+SDKs#Backlog

2024-03-14 17:59 UTC, Mercy811 commented on docs/data/sdks/flutter/migration.md
> ++ amplitude.identify(identify);
`;` is required. line 161, 162, and 163 are the same line of code. See https://dart.dev/language/operators#cascade-notation.

2024-03-14 18:00 UTC, Mercy811 commented on mkdocs.yml
> +        # - Migration Guide: data/sdks/flutter/migration.md
See https://github.com/amplitude/amplitude-dev-center/pull/239#discussion_r1522202724. I will uncomment this at the PR of the doc of the new Flutter SDK.

2024-03-14 18:03 UTC, yuhao900914 commented on docs/data/sdks/flutter/migration.md
> ++ amplitude.identify(identify);
I saw other examples do not have `;`, could you add all?

2024-03-14 18:03 UTC, yuhao900914 commented on mkdocs.yml
> +        # - Migration Guide: data/sdks/flutter/migration.md
Got it. It's make sense.

2024-03-14 18:27 UTC, Mercy811 commented on docs/data/sdks/flutter/migration.md
> ++ amplitude.identify(identify);
Added at https://github.com/amplitude/amplitude-dev-center/pull/239/commits/a11189de6e73b34fea2b84edcc6a8e14da5fdc5c

2024-03-14 18:46 UTC, yuhao900914 approved these changes

2024-03-14 20:25 UTC, merged