feat: add session handling for Kotlin and Swift
amplitude/amplitude-dev-center pull request #24
Opened 2023-10-05 23:03 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

https://amplitude.atlassian.net/browse/AMP-86240

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-05 23:24 UTC, markzegarelli requested changes

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +Amplitude starts a session when the app is brought into the foreground or when an event is tracked in background.
```suggestion
Amplitude starts a session when the app is brought into the foreground or when an event is tracked in the background.
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +Amplitude tracks a session start event upon entering the foreground and starts a countdown set by `setMinTimeBetweenSessionsMillis()`. If a new event is tracked, Amplitude extends the session and res
```suggestion
When the app enters the foreground, Amplitude tracks a session start, and starts a countdown based on `setMinTimeBetweenSessionsMillis()`. Amplitude extends the session and restarts the countdown any time it tracks a new event. If the countdown expires, Amplitude waits until the next event to track a session end event.
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +Amplitude SDKs don't set user properties to session events directly. Instead `identify()` and `setUserId()` update user properties from the SDK. The user property state is then aggregated on the back
```suggestion
Amplitude doesn't set user properties on session events by default. To add these properties, use `identify()` and `setUserId()`. Amplitude aggregates the user property state and associates the user with events based on `device_id` or `user_id`.
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +If they would like to not sync user properties on these events we have an option of setting "$skip_user_properties_sync": true on the event, and this will stop us from syncing properties on that even
```suggestion
If you don't want to sync user properties with session events, set the `$skip_user_properties_sync` property to `true` to instruct Amplitude to stop syncing properties on that particular event.
```
@Mercy811 Where would someone set $skip_user_properties_sync?

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +Due to how Amplitude manages sessions, there are certain scenarios where the SDK works expected but may appear as if events are missing or session tracking is inaccurate:
```suggestion
Due to the way in which Amplitude manages sessions, there are scenarios where the SDK works expected but it may appear as if events are missing or session tracking is inaccurate:
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +* If a user never returns to the app , there will be no corresponding session end event for the session start event
```suggestion
* If a user doesn't return to the app, Amplitude does not track a session end event to correspond with a session start event.
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +* If you disable session tracking and only track few events in the app, the tracked session length will be shorter than the time the user actually spends on the app
```suggestion
* If you disable session tracking and track a minimal number of events, Amplitude perceives the session length to be shorter than the user spends on the app.
```

2023-10-05 23:24 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +* If you modify user properties between the last event and the session end event, the session end event will reflect the updated user properties, potentially differing from other properties associate
```suggestion
* If you modify user properties between the last event and the session end event, the session end event reflects the updated user properties, which may differ from other properties associated with events in the same session. To address this, use an enrichment plugin to set `$skip_user_properties_sync` to `true` on the session end event, which prevents Amplitude from synchronizing properties for that specific event.


```

2023-10-06 15:49 UTC, justin-fiedler requested changes

2023-10-06 15:49 UTC, justin-fiedler commented on includes/sdk-next-gen-mobile-session.md
> +Amplitude tracks a session start event upon entering the foreground and starts a countdown set by `setMinTimeBetweenSessionsMillis()`. If a new event is tracked, Amplitude extends the session and res
Can you please clarify that the `setMinTimeBetweenSessionsMillis(). e.g. Sessions will continue for the entire time the app is in the foreground, if the app is in the background for more than "min time between sessions" a new session will be started the next time the user opens the app, or tracks an event in the background.

2023-10-06 17:00 UTC, Mercy811 commented on includes/sdk-next-gen-mobile-session.md
> +If they would like to not sync user properties on these events we have an option of setting "$skip_user_properties_sync": true on the event, and this will stop us from syncing properties on that even
Make it up at https://github.com/amplitude/amplitude-dev-center/pull/24/commits/fea9c627ae0b117cff48d169fee5f81f79aa9ba9

2023-10-06 17:01 UTC, Mercy811 commented on includes/sdk-next-gen-mobile-session.md
> +Amplitude tracks a session start event upon entering the foreground and starts a countdown set by `setMinTimeBetweenSessionsMillis()`. If a new event is tracked, Amplitude extends the session and res
Change at https://github.com/amplitude/amplitude-dev-center/pull/24/commits/95a11e43b07a65ed091268f3948358c1270f61df. WDYT?

2023-10-06 17:23 UTC, markzegarelli commented on includes/sdk-next-gen-mobile-session.md
> +* If you modify user properties between the last event and the session end event, the session end event reflects the updated user properties, which may differ from other properties associated with ev
```suggestion
* If you modify user properties between the last event and the session end event, the session end event reflects the updated user properties, which may differ from other properties associated with events in the same session. To address this, use an enrichment plugin to set `event['$skip_user_properties_sync']` to `true` on the session end event, which prevents Amplitude from synchronizing properties for that specific event. See [$skip_user_properties_sync](/data/sdks/flutter/#skip_user_properties_sync) in the Flutter SDK article to learn more.
```

2023-10-06 23:04 UTC, markzegarelli approved these changes

2023-10-11 15:54 UTC, justin-fiedler approved these changes

2023-10-17 06:02 UTC, merged