SKY-4743 Add dev docs for Contentful integration
amplitude/amplitude-dev-center pull request #249
Opened 2024-03-14 22:01 UTC by hthr-lee

# Amplitude Developer Docs PR

## Description
These are dev docs for the Contentful integration for the first beta users.

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [x] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-03-14 22:37 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +- Read different properties (refreshed regularly) from Amplitude Experiment and build your content around this information
how often is `refreshed regularly`?

2024-03-14 22:37 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +- Run A/B tests and multi armed bandit experiments on Amplitude Experiment and author content in Contentful
do we want to wait until multi armed bandit is GAed to add that?

2024-03-14 22:38 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +---
What does the rollout for Conteful look like? Are you okay adding this to dev docs if it is not rolled out to 100%?

2024-03-14 22:41 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +- Run A/B tests and multi armed bandit experiments on Amplitude Experiment and author content in Contentful
Ooh yeah, let me remove that for now.

2024-03-14 22:42 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +- Read different properties (refreshed regularly) from Amplitude Experiment and build your content around this information
Every 5 seconds! Should I add this?

2024-03-14 22:44 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +Provide your management API key created in the Getting Started section. Note: This management API key will no longer be visible to others looking at this app configuration once you install the app.
do you want to add anything other than `Note: This management API key will no longer be visible to others looking at this app configuration once you install the app.` to make people who are worried about security less worried about things like exposing the management API key to a 3rd party that could use this maliciously.

2024-03-14 22:45 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +Provide your management API key created in the Getting Started section. Note: This management API key will no longer be visible to others looking at this app configuration once you install the app.
Out of scope for your current work: Do we want to make the management API key only have permissions to the routes you need for contentful and not have it have all permissions

2024-03-14 22:46 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +Type in your Org URL (if you are not sure, check out your url: `https://app.amplitude.com/experiment/<ORG_URL>/dashboard`).
nit: for EU, it is eu.app.amplitude.com. But not sure how we deal with that elsewhere in dev docs? @markzegarelli

2024-03-14 22:46 UTC, bgiori commented on docs/experiment/integrations/contentful.md
> +---
I would put a closed beta tag at the top of the doc.

```
!!!beta "Closed Beta"
    The Amplitude Experiment Contentful plugin is in closed beta. Contact your Amplitude representative or email experiment@amplitude.com if you're interested.
```

2024-03-14 22:48 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +title: Contentful Plugin for Amplitude Experiment
Is the contentful integration only for experiment of for flags also?

2024-03-14 22:51 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +```typescript
nit: can we get syntax highlighting on the dev docs site?

2024-03-14 22:53 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +
Do we want to make any callouts about remembering that some users may get "off"? Especially, if non-engineers are going to be using Contentful they may forget about that case

2024-03-14 22:56 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +- Read different properties (refreshed regularly) from Amplitude Experiment and build your content around this information
sure you can add it. unless you think it is going to change in the future

2024-03-15 16:16 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +Type in your Org URL (if you are not sure, check out your url: `https://app.amplitude.com/experiment/<ORG_URL>/dashboard`).
We should list both.

2024-03-15 16:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +```typescript
We have syntax highlighting with Pygments. It is admittedly pretty poor. For the new version of the docs site in development right now, we're moving to Torchlight.

2024-03-15 17:59 UTC, markzegarelli requested changes
Initial feedback:

- Let's remove screenshots. In general, we avoid screenshots in apps that aren't ours, as the UI can change without us knowing about it, causing our docs to become out of date.
- Heading level should start at h2, not h3.

I'll provide a more thorough review once other comments are resolved.

2024-03-15 17:59 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +When it comes to feature flag delivery and experimentation, one size does not fit all. Amplitude Experiment is built for flexibility to fit in with any architecture and a variety of needs. This app o
```suggestion
Amplitude Experiment is built for flexibility to fit in with any architecture and a variety of needs. This app offers an easy and flexible way to build out your content on top of Amplitude Experiment to help grow your marketing efforts.
```

We should mention Contentful specifically in this opening paragraph.

2024-03-15 17:59 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +To use this app, you will need access to an Amplitude plan with Amplitude Experiment enabled. You will need a Management API key which you can find [instructions on how to configure here](https://www
```suggestion
To use this plugin, you'll need the following:

- Access to an Amplitude plan with Amplitude Experiment enabled. 
- A Management API key, which you can find in the Experiment side bar.
```
The link provided doesn't expand on much about Management API Keys.

2024-03-15 17:59 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +In order to integrate your Contentful instance with Amplitude Experiment, you will need:
```suggestion
To integrate your Contentful instance with Amplitude Experiment, you will need:
```

This is duplicative of the Requirements section above. Recommend removing the former.

2024-03-15 17:59 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +### Getting Started
```suggestion
## Getting Started
```

2024-03-20 16:57 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +title: Contentful Plugin for Amplitude Experiment
Just for experiment for now. If there's enough customer demand we can extend this to flags too.

2024-03-20 16:58 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +Type in your Org URL (if you are not sure, check out your url: `https://app.amplitude.com/experiment/<ORG_URL>/dashboard`).
This was actually just to show the user how to find their ORG_URL from their URL in the browser. Is there a better way to describe how the user gets their ORG_URL?

2024-03-20 17:00 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +Provide your management API key created in the Getting Started section. Note: This management API key will no longer be visible to others looking at this app configuration once you install the app.
I agree with you that the permissioning for the management API key can be improved! Will address your first comment.

2024-03-20 17:01 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +Type in your Org URL (if you are not sure, check out your url: `https://app.amplitude.com/experiment/<ORG_URL>/dashboard`).
this is fine. you can also go here https://app.amplitude.com/analytics/amplidemo/settings/plan-admin to find the org url. Replace amplidemo with your org url

2024-03-20 17:04 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +
Just added the blurb below, let me know if that can be worded better.

2024-03-20 18:19 UTC, markzegarelli requested changes
@hthr-lee Please resolve any open comments and requested changes, and I will make edits directly to the source.

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +## Getting Started
Let's remove this section. You list the requirements above.

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +### Requirements
```suggestion
## Requirements
```

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +### Features
```suggestion
## Features
```

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +Amplitude Experiment is built for flexibility to fit in with any architecture and a variety of needs. This app offers an easy and flexible way to build out your content on top of Amplitude Experiment
The intro should mention Contentful. This reads like an introduction to Experiment only.

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +Provide your management API key created in the Getting Started section. Note: This management API key will no longer be visible to others on your team looking at this app configuration in the UI once
```suggestion
Provide your management API key created in the Getting Started section.  For security purposes, management API keys aren't visible to others on your team looking  once you install the app.
```

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +You should now be able to see a Content model in Contentful under the Content model tab called “Variation Container.”
```suggestion
You should see a Content model in Contentful on the **Content model** tab called “Variation Container.”
```

What is called "Variation Container"? The content model?

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +### How to install
```suggestion
## Installation
```

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +#### Step 1 - Install the app in your Contentful instance under the Apps tab
```suggestion
### Step 1 - Install the app in your Contentful instance under the Apps tab
```

2024-03-20 18:19 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +#### Step 2 - Add a variation container to one of your content models
```suggestion
### Step 2 - Add a variation container to one of your content models
```

2024-03-20 18:43 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +
looks good

2024-03-20 18:48 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +- [A management API key](https://www.docs.developers.amplitude.com/guides/amplitude-keys-guide/?h=keys#management-api-key)
do we have any permissions checks for who can create management API keys? Do you have to be admin? Do we want to include that in this doc?

2024-03-20 22:52 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +You should now be able to see a Content model in Contentful under the Content model tab called “Variation Container.”
Yes, the content model in Contentful is called "Variant Container." Heads up that I just updated the name from "Variation Container" to "Variant Container."

2024-03-20 22:55 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +- [A management API key](https://www.docs.developers.amplitude.com/guides/amplitude-keys-guide/?h=keys#management-api-key)
Since we link to the management API docs for the key I don't think we need to add more details here: https://www.docs.developers.amplitude.com/guides/amplitude-keys-guide/?h=keys#management-api-key

2024-03-20 23:02 UTC, akhil-prakash commented on docs/experiment/integrations/contentful.md
> +Provide your management API key created in the Getting Started section.  For security purposes, management API keys aren't visible to others on your team looking  once you install the app.
nit: one space between "looking" and "once"

2024-03-20 23:02 UTC, akhil-prakash approved these changes

2024-03-22 18:49 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +Amplitude Experiment is built for flexibility to fit in with any architecture and a variety of needs. This app offers an easy and flexible way to build out your content on top of Amplitude Experiment
Just added some more details around Contentful. Can you please take a look @markzegarelli? Thanks!

2024-03-26 19:11 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
>  ## Installation
```suggestion
## Installation and use
```

2024-03-26 19:14 UTC, markzegarelli commented
@hthr-lee I just pushed a big edit. Please have a look and let me know what you think

Also, we're missing the piece of this that tells users where to find and how to install the plugin. WIll this be available in the Contentful Marketplace? Or are we distributing it through other means?

2024-03-26 19:58 UTC, hthr-lee commented
@markzegarelli We don't want to GA this right now. The user will receive a link if they follow the instructions listed here: https://github.com/amplitude/amplitude-dev-center/pull/249/files#diff-c18ebe11aab8d0938d4a850fe32e1a53abaaa98d3cf2526c776445ce7accd725R6

2024-03-26 19:59 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +1. In Contentful, search for #### in the Contentful App Marketplace. Click #### to install the plugin.
The app is currently not publicly listed in the Contentful App Marketplace and will instead be shared via a link when the user contacts experiment@amplitude.com if they are interested.

2024-03-26 20:00 UTC, hthr-lee commented
The changes you made look good to me @markzegarelli besides the marketplace comment!

2024-03-26 20:18 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +1. In Contentful, search for #### in the Contentful App Marketplace. Click #### to install the plugin.
@hthr-lee Cool! What status will this release under? I'll add an admonition at the top, and explain the need to contact the team to get the plugin.

It's best practice that once a user gets to installation instructions, they should be able to move through them right away, so we want to call out the need to contact the team higher in the doc.

2024-03-26 20:24 UTC, hthr-lee commented on docs/experiment/integrations/contentful.md
> +1. In Contentful, search for #### in the Contentful App Marketplace. Click #### to install the plugin.
It should be under `closed beta` status. I added something here: https://github.com/amplitude/amplitude-dev-center/pull/249/files#diff-c18ebe11aab8d0938d4a850fe32e1a53abaaa98d3cf2526c776445ce7accd725R6 feel free to change it!

2024-03-26 20:56 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +1. In Contentful, search for #### in the Contentful App Marketplace. Click #### to install the plugin.
```suggestion
1. Install the plugin you receive from the Amplitude Experiment team.
```

2024-03-26 20:57 UTC, markzegarelli commented on docs/experiment/integrations/contentful.md
> +- Access to an Amplitude plan with Amplitude Experiment enabled.
```suggestion
- Access to an Amplitude plan with Amplitude Experiment enabled.
- The Contentful Plugin for Amplitude Experiment, to be sent by the Amplitude Experiment team.
```

2024-03-26 20:57 UTC, markzegarelli approved these changes

2024-03-26 21:08 UTC, merged