Create sleekflow-cohort.md
amplitude/amplitude-dev-center pull request #25
Opened 2023-10-06 11:49 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-06 16:27 UTC, markzegarelli requested changes

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +    This integration is currently in beta and is in active development. This integration is maintained by Master Concept Group. Contact the Master Concept Team by emailing <digital_lab@hkmci.com> for
```suggestion
    This integration is in beta and is in active development. The integration is maintained by Master Concept Group. For support or questions about the integration, contact the Master Concept team directly at [digital_lab@hkmci.com](mailto:digital_lab@hkmci.com).
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +[Sleekflow](https://sleekflow.io/) is an Omni-Channel Social Engagement Platform that helps companies and users manage communication channels such as WhatsApp, Facebook Messenger, WeChat, Line, and I
```suggestion
[Sleekflow](https://sleekflow.io/) is an Omni-Channel Social Engagement Platform that helps companies and users manage communication channels like WhatsApp, Facebook Messenger, WeChat, Line, and Instagram. Sleekflow handles both inbound messaging management as well as outbound messaging campaigns. This integration lets you sync cohorts from Amplitude to Sleekflow. 
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +- This integration is only available by request. Email <digital_lab@hkmci.com> to request access.
```suggestion
- This integration is available by request. Email [digital_lab@hkmci.com](mailto:digital_lab@hkmci.com) to request access.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +- Sleekflow requires at least an email address or a phone number as the unique contact identifier. The phone number needs to have a country code (the ‘+’ in front of the country code is optional). Th
```suggestion
- Sleekflow requires at least an email address or a phone number as the unique contact identifier. The phone number must include a country code (the `+` in front of the country code is optional). This means the `user_ID` or user property you select in Amplitude must contain an email address or phone number.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +3. Click "Connect" next to "API"
```suggestion
3. Click **Connect** next to **API**.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +1. Log into Sleekflow.
```suggestion
1. Log in to Sleekflow.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +4. Copy the API Key to your clipboard.
```suggestion
4. Copy the Sleekflow API Key.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +2. In the Cohort section, click **Sleekflow**.
@Brandoncharleskhoo1 Is this integration available to everyone in Amplitude? If so, does the request to Sleekflow mentioned on line 15 enable the Sleekflow setup steps?

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +To sync your first cohort, follow these steps:
```suggestion
To sync your first cohort:
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +1. **Personalized Push Notifications:**  By integrating Amplitude cohorts with Sleekflow, you can send personalized messages to different user segments based on their behavior and preferences. For ex
```suggestion
1. **Personalized Push Notifications:**  When you integrate Amplitude cohorts with Sleekflow, you can send personalized messages to different user segments based on their behavior and preferences. For example, you can create a cohort of users who have abandoned their shopping carts then send them targeted reminders or incentives through WhatsApp, Facebook Messenger, or other communication channels that Sleekflow supports. 
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +2. **Re-Engagement Campaigns:** You can use Amplitude cohorts to identify users who haven't interacted with your brand for a certain period. Sleekflow can help you send re-engagement messages to thes
```suggestion
2. **Re-Engagement Campaigns:** Use Amplitude cohorts to identify users who haven't interacted with your brand for a certain period. Sleekflow can send re-engagement messages to these cohorts through supported social media channels, encouraging them to revisit your platform and make a purchase.
```

2023-10-06 16:27 UTC, markzegarelli commented on docs/data/destinations/sleekflow-cohort.md
> +3. **Product Recommendations:** Leverage Amplitude's user behavior data to create cohorts of users with similar product interests. Then, use Sleekflow to send product recommendations and promotions t
```suggestion
3. **Product Recommendations:** Use Amplitude's user behavior data to create cohorts of users with similar product interests. Then, use Sleekflow to send product recommendations and promotions to these cohorts through channels like Instagram or Facebook Messenger, increasing the likelihood of conversions.
```

2023-10-11 19:02 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/sleekflow-cohort.md
> +2. In the Cohort section, click **Sleekflow**.
Hi Mark, this integration is only available if Sleekflow approves it.

2023-10-11 19:29 UTC, markzegarelli approved these changes

2023-10-12 06:57 UTC, merged