update default session event tracking
amplitude/amplitude-dev-center pull request #253
Opened 2024-03-18 20:43 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

https://amplitude.atlassian.net/browse/AMP-93957

It's misleading to say "session tracking is disabled when `config.defaultTracking.sessions`" because it only disables tracking default session events, session Id is still working.

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-03-18 20:46 UTC, izaaz approved these changes

2024-03-18 20:49 UTC, markzegarelli requested changes

2024-03-18 20:49 UTC, markzegarelli commented on docs/data/sdks/android-kotlin/index.md
> +    `config.defaultTracking.sessions` | Optional. `boolean` | `true` | Enables session tracking. This configuration replaces [`trackingSessionEvents`](#configuration). If value is `true`, Amplitude t
```suggestion
    `config.defaultTracking.sessions` | Optional. `boolean` | `true` | Enables session tracking. This configuration replaces [`trackingSessionEvents`](#configuration). If value is `true`, Amplitude tracks session start and session end events otherwise, Amplitude doesn't track session events. When this setting is `false`, Amplitude tracks `sessionId` only.<br /><br />See [Tracking sessions](#tracking-sessions) for more information.|
```

2024-03-18 20:49 UTC, markzegarelli commented on docs/data/sdks/browser-2/index.md
> +    `config.defaultTracking.sessions` | Optional. `boolean` | Enables/disables session tracking. If value is `true`, Amplitude tracks session start and session end events otherwise session events are
```suggestion
    `config.defaultTracking.sessions` | Optional. `boolean` | Enables/disables session tracking. If value is `true`, Amplitude tracks session start and session end events otherwise, Amplitude doesn't track session events. When this setting is `false`, Amplitude tracks `sessionId` only.<br /><br />See [Tracking sessions](#tracking-sessions) for more information.|
```

2024-03-18 20:49 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +`defaultTracking.sessions` | Optional. `boolean` | `true` | Enables session tracking. This configuration replaces [`trackingSessionEvents`](#configuration). If value is `true`, Amplitude tracks sessi
```suggestion
`defaultTracking.sessions` | Optional. `boolean` | `true` | Enables session tracking. This configuration replaces [`trackingSessionEvents`](#configuration). If value is `true`, Amplitude tracks session start and session end events otherwise, Amplitude doesn't track session events. When this setting is `false`, Amplitude tracks `sessionId` only.<br /><br />See [Tracking sessions](#tracking-sessions) for more information.|
```

2024-03-18 23:39 UTC, markzegarelli approved these changes

2024-03-19 15:45 UTC, justin-fiedler approved these changes

2024-03-19 15:58 UTC, merged