event properties object instruction
amplitude/amplitude-dev-center pull request #261
Opened 2024-03-25 10:26 UTC by yuhao900914

# Amplitude Developer Docs PR

## Description

Describe your changes. 
Add instructions for the GTM event properties object input. 

<img width="643" alt="Screenshot 2024-03-25 at 3 25 57 AM" src="https://github.com/amplitude/amplitude-dev-center/assets/13028329/bd20f02f-7896-444e-b256-2732a7f5cf56">

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-03-25 16:32 UTC, markzegarelli requested changes

2024-03-25 16:32 UTC, markzegarelli commented on docs/data/sources/google-tag-manager-client.md
> +Choose the object format for the GTM variable to define event properties. It's important to note that if there are any duplicate keys, the event properties object will overwrite the basic event prope
```suggestion
Choose the object format for the GTM variable to define event properties. Use unique values for keys in the object. Amplitude overwrites any basic event properties that have duplicate keys. Amplitude ignores any inputs not in the object format.
```

2024-04-24 01:16 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +Choose the object format for the GTM variable to define event properties. It's important to note that if there are any duplicate keys, the event properties object will overwrite the basic event prope
Thanks for reviewing @markzegarelli .
Basically, there are 2 event properties. **EVENT PROPERTIES BASIC** and **EVENT PROPERTIES OBJECT**. I What I want to clarify here is if there is a duplicate key between **EVENT PROPERTIES BASIC** and **EVENT PROPERTIES OBJECT**, the value in **EVENT PROPERTIES OBJECT** will overwrite the value in **EVENT PROPERTIES BASIC**.  

I feel here is a misunderstanding.

2024-04-25 21:17 UTC, markzegarelli requested changes

2024-04-25 21:17 UTC, markzegarelli commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This will overwrite the **Event Properties Basic** event properties if there has any duplicate key. Amplitude ignores any inputs no
```suggestion
Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not in the object format.
```

2024-04-25 21:18 UTC, markzegarelli approved these changes

2024-04-26 17:26 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +Choose the object format for the GTM variable to define event properties. It's important to note that if there are any duplicate keys, the event properties object will overwrite the basic event prope
Thanks @markzegarelli.
The feature has not been published yet, I will merge this PR after the feature release.

2024-04-26 20:51 UTC, izaaz commented on docs/data/sources/google-tag-manager-client.md
> +##### Event Properties Basic
Should we call this Event properties key value pairs?

2024-04-26 20:52 UTC, izaaz commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not i
Can we call out the Google variable that has both event properties and user properties in it? And provide an example of what that looks like and what will be ignored in that object.

2024-04-26 20:53 UTC, izaaz commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not i
And actually, we should just advice that they use that variable always to keep it simple.

2024-04-27 00:03 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +##### Event Properties Basic
I think both ways are setting the key-value pair. But the difference is it's by individual or bulk set. 
I use individual operation vs Bulk set operation for the identify properties. How do you like it?
May be here we use  **Individual Event Properties**?

2024-04-27 01:22 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not i
Added another shared section to introduce **Google Tag: Event Settings** and added it to both the user properties and event properties section.

2024-04-30 17:51 UTC, izaaz commented on docs/data/sources/google-tag-manager-client.md
> +##### Event Properties Basic
Yea maybe lets go with individual event properties.

2024-05-02 20:20 UTC, izaaz commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not i
```suggestion
Select a GTM variable that returns a valid event properties object. This overwrites the **Individual event properties** if there are any duplicate keys. Amplitude ignores any inputs not in the object format and any value under `user_properties` key.
```

2024-05-02 20:21 UTC, izaaz approved these changes

2024-05-02 20:25 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +Select a GTM variable that returns a valid event properties object. This overwrites the **Event Properties Basic** event properties if there are any duplicate keys. Amplitude ignores any inputs not i
fixed.

2024-05-03 00:41 UTC, merged