add more info on `delete_from_org`
amplitude/amplitude-dev-center pull request #265
Opened 2024-03-25 18:51 UTC by robynnason

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-03-25 20:02 UTC, markzegarelli requested changes

2024-03-25 20:50 UTC, markzegarelli approved these changes

2024-03-29 17:30 UTC, nwangtw approved these changes

2024-04-19 17:01 UTC, robynnason commented
@markzegarelli @nwangtw made updates based on internal discussion on the appropriate language and clarity

2024-04-19 17:13 UTC, nwangtw commented on docs/analytics/apis/user-privacy-api.md
> +- By default, deletion requests create jobs for a particular project within your organization. API calls identify this project with the api key you provide in the request. To delete a user across you
"set both the `delete_from_org` and `ignore_invalid_ids` parameters to `true` in your request."

I think "and `ignore_invalid_ids` parameters "  is not needed

2024-04-19 17:20 UTC, nwangtw commented on docs/analytics/apis/user-privacy-api.md
> +| `delete_from_org`                  | Boolean. Defaults to `false`. When `false`, the request will only delete the requested users from the project identified by the given API key. When set to `true
there are 3 sentences start with "When `true`" or `When set to `true`". I am wondering if we can rephrase it a little.

2024-04-19 17:27 UTC, robynnason commented on docs/analytics/apis/user-privacy-api.md
> +| `delete_from_org`                  | Boolean. Defaults to `false`. When `false`, the request will only delete the requested users from the project identified by the given API key. When set to `true
reworded a bit, lmk what you think

2024-04-19 21:23 UTC, nwangtw commented on docs/analytics/apis/user-privacy-api.md
> +Amplitude recommends setting this to `true` if setting the `delete_from_org` parameter to `true`
This should be removed?

2024-04-19 21:33 UTC, nwangtw commented on docs/analytics/apis/user-privacy-api.md
> +    -U 'API_KEY:SECRET_KEY' \
lower case

2024-04-23 22:41 UTC, merged