AMP-96862 [DatabricksImport] Update the developer doc for databricks import
amplitude/amplitude-dev-center pull request #275
Opened 2024-04-01 23:00 UTC by bh202205

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-04-01 23:03 UTC, bh202205 commented on docs/data/sources/databricks.md
>  - User stream view isn't available for data ingested with this feature.
hey @shawn-amplitude do you know if this is still true?

2024-04-01 23:06 UTC, markzegarelli requested changes

2024-04-01 23:06 UTC, markzegarelli commented on docs/data/sources/databricks.md
> +```
```suggestion
```json
```

2024-04-01 23:06 UTC, markzegarelli commented on docs/data/sources/databricks.md
> +Ensure that the new cluster is able to run jobs by NOT having configs below in cluster's policy. See details in [doc](https://docs.databricks.com/en/administration-guide/clusters/policy-definition.ht
```suggestion
Ensure that the new cluster can run jobs by NOT having configs below in cluster's policy. See details in Databricks' article [Policy definition](https://docs.databricks.com/en/administration-guide/clusters/policy-definition.html#workload).
```

2024-04-01 23:08 UTC, fzqgriffin commented on docs/data/sources/databricks.md
> +- Databricks import doesn't support export data.
then let's probably remove. `databricks import` is only for bringing data from databricks to Amplitude. `databricks export` will be a separate feature which has no dependency on `databricks import` so we don't need to mention that.

2024-04-02 16:51 UTC, markzegarelli requested changes

2024-04-02 16:51 UTC, markzegarelli commented on docs/data/sources/databricks.md
> +```
@bh202205 We need `json` on line 35. Formatting breaks otherwise.

2024-04-02 16:51 UTC, markzegarelli commented on docs/data/sources/databricks.md
> +```json
```suggestion
```
```

2024-04-02 16:59 UTC, markzegarelli approved these changes

2024-04-02 17:18 UTC, merged