feat: add apple privacy manifest
amplitude/amplitude-dev-center pull request #276
Opened 2024-04-01 23:59 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

https://amplitude.atlassian.net/browse/AMP-92244

Add privacy manifest section for Amplitude-Swift. 
Reference:
- https://www.revenuecat.com/docs/platform-resources/apple-platform-resources/apple-app-privacy#required-data-types
- https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/ios-17/

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [x] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-04-02 00:06 UTC, izaaz commented on docs/data/sdks/ios-swift/index.md
> +Starting December 8, 2020, Apple requires a privacy manifest file for all new apps and app updates and Apple expects to make it mandatory in the Spring of 2024. As Amplitude is a third-party to your
dec 8 2020?

2024-04-02 00:09 UTC, Mercy811 commented on docs/data/sdks/ios-swift/index.md
> +Starting December 8, 2020, Apple requires a privacy manifest file for all new apps and app updates and Apple expects to make it mandatory in the Spring of 2024. As Amplitude is a third-party to your
Yes. https://developer.apple.com/news/?id=em8fm29e

2024-04-02 16:41 UTC, markzegarelli requested changes

2024-04-02 16:41 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +Starting December 8, 2020, Apple requires a privacy manifest file for all new apps and app updates and Apple expects to make it mandatory in the Spring of 2024. As Amplitude is a third-party to your
```suggestion
Starting December 8, 2020, Apple requires a privacy manifest file for all new apps and app updates. Apple expects to make this mandatory in the Spring of 2024. As Amplitude is a third-party to your app, you need to ensure you properly disclose to your users the ways you use Amplitude in regards to their data.
```

2024-04-02 16:41 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +    Amplitude sets privacy manifest based on the default configuration. Update the privacy manifest according to your configuraiton and your app.
```suggestion
    Amplitude sets privacy manifest based on a default configuration. Update the privacy manifest according to your configuration and your app.
```

2024-04-02 16:41 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +    Tracking refers to the act of linking user or device data collected from your app with user or device data collected from other companies' apps, websites, or offline properties for targeted adver
```suggestion
    Tracking refers to the act of linking user or device data collected from your app with user or device data collected from other companies' apps, websites, or offline properties for targeted advertising or advertising measurement purposes. For more information, see Apple's article [User privacy and data use](https://developer.apple.com/app-store/user-privacy-and-data-use/).
```

2024-04-02 16:41 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +Amplitude by default doesn't use data for tracking. Add this field and set it to true if your app does.
```suggestion
By default, Amplitude doesn't use data for tracking. Add this field and set it to true if your app does.
```

2024-04-02 16:41 UTC, markzegarelli commented on docs/data/sdks/ios-swift/index.md
> +By default the SDK tracks device Id only, but you can track user Id as well by `amplitude.setUserId()`. To do so, you have to add "User ID" Data type. See all data types [here](https://developer.appl
```suggestion
By default the SDK tracks `deviceId` only. You can use `amplitude.setUserId()` track `userId` as well. To do so, add the "User ID" Data type. For more information about data types, see Apple's article [Describing data use in privacy manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests).
```

2024-04-02 22:37 UTC, Mercy811 commented on docs/data/sdks/ios-swift/index.md
> +Starting December 8, 2020, Apple requires a privacy manifest file for all new apps and app updates and Apple expects to make it mandatory in the Spring of 2024. As Amplitude is a third-party to your
Thanks @markzegarelli. I will avoid using future tense.

2024-04-02 23:42 UTC, markzegarelli approved these changes

2024-04-03 17:24 UTC, izaaz commented on docs/data/sdks/ios-swift/index.md
> +By default the SDK tracks `deviceId` only. You can use `amplitude.setUserId()` track `userId` as well. To do so, add the "User ID" Data type. For more information about data types, see Apple's articl
You can use `amplitude.setUserId()` *to* track ...

2024-04-03 17:58 UTC, crleona approved these changes

2024-04-03 17:58 UTC, crleona commented on docs/data/sdks/ios-swift/index.md
> +|Coarse Location|Yes|No|Analytics|
we may want to call out this is based on ip geolocation, and not something we collect from device gps/location features.

2024-04-03 17:58 UTC, crleona commented on docs/data/sdks/ios-swift/index.md
> +#### NSPrivacyTrackingDomains
I'm not sure if we want to include these by default - Consider an app that is tracking users, but not through Amplitude, instead just relying on us for analytics. The [docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) imply that requests to our domains would be blocked if the user requests not to be tracked. Perhaps we add these as a suggestion on the docs for customers that are actually tracking through us?

2024-04-03 18:52 UTC, Mercy811 commented on docs/data/sdks/ios-swift/index.md
> +#### NSPrivacyTrackingDomains
> If you set NSPrivacyTracking to true then you need to provide at least one internet domain in NSPrivacyTrackingDomains; otherwise, you can provide zero or more domains.

It makes sense to not have tracking domains by default. There is PR to update the privacy manifest https://github.com/amplitude/Amplitude-Swift/pull/155

2024-04-03 19:24 UTC, Mercy811 commented on docs/data/sdks/ios-swift/index.md
> +|Coarse Location|Yes|No|Analytics|
I added a column to explain where each filed is tracked at https://github.com/amplitude/amplitude-dev-center/pull/276/commits/917fd497a7804eb9eb357885cc221433f9a2f70f
![image](https://github.com/amplitude/amplitude-dev-center/assets/31029607/6b16a414-e44e-4c11-94f7-5dcf761d958e)

2024-04-03 19:28 UTC, crleona commented on docs/data/sdks/ios-swift/index.md
> +#### NSPrivacyTrackingDomains
Thanks!

2024-04-03 19:28 UTC, crleona approved these changes

2024-04-03 19:28 UTC, Mercy811 commented on docs/data/sdks/ios-swift/index.md
> +#### NSPrivacyTrackingDomains
Updated docs at https://github.com/amplitude/amplitude-dev-center/pull/276/commits/a6d068b405bdb6f9af830ea6ce56e26a1f98a936

2024-04-03 19:30 UTC, merged