react native local evaluation
amplitude/amplitude-dev-center pull request #29
Opened 2023-10-09 17:42 UTC by bgiori

# Amplitude Developer Docs PR

## Description

SDK doc update for react native client-side local evaluation

## Deadline

(Tuesday)

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-10 16:36 UTC, markzegarelli requested changes

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +    The right way to initialize the Experiment SDK depends on whether you use an
```suggestion
    The correct way to initialize the Experiment SDK depends on whether you use an
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +    Amplitude SDK for analytics or a third party (e.g. Segment).
```suggestion
    Amplitude SDK for analytics or a third party tool like Segment.
```
Not sure why this is wrapped onto a new line.

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +The SDK client can be configured once on initialization.
```suggestion
SDK client configuration occurs during initialization.
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +    | `automaticExposureTracking` | If true, calling [`variant()`](#variant) will track an exposure event through the configured `exposureTrackingProvider`. If no exposure tracking provider is set, t
```suggestion
    | `automaticExposureTracking` | If true, calling [`variant()`](#variant) tracks an exposure event through the configured `exposureTrackingProvider`. If no exposure tracking provider is set, this configuration option does nothing.  | `true` |
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +    | `automaticFetchOnAmplitudeIdentityChange` | Only matters if you use the `initializeWithAmplitudeAnalytics` initialization function to seamlessly integrate with the Amplitude Analytics SDK. If `
```suggestion
    | `automaticFetchOnAmplitudeIdentityChange` | Only matters if you use the `initializeWithAmplitudeAnalytics` initialization function to seamlessly integrate with the Amplitude Analytics SDK. If `true` any change to the user ID, device ID or user properties from analytics triggers the experiment SDK to fetch variants and update it's cache. | `false` |
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +If you use either Amplitude or Segment Analytics SDKs to track events into Amplitude, you'll want to set up an integration on initialization. Integrations automatically implement [provider](#provider
```suggestion
If you use either Amplitude or Segment Analytics SDKs to track events into Amplitude, Amplitude recommends that you set up an integration on initialization. Integrations implement [provider](#providers) interfaces to enable a more streamlined developer experience by making it easier to **manage user identity** and **track exposures events**.
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +Start the SDK by getting flag configurations from the server and fetching remote evaluation variants for the user. The SDK is ready once the returned promise resolves.
```suggestion
The Experiment SDK starts when you get flag configurations from the server and fetch remote evaluation variants for the user. The SDK is ready after the returned promise resolves.
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +| `user` | optional | Explicit [user](../general/data-model.md#users) information to pass with the request to fetch variants. This user information is merged with user information provided from [inte
```suggestion
| `user` | optional | Explicit [user](../general/data-model.md#users) information to pass with the request to fetch variants. This user information merges with user information from any [integrations](#integrations) through the [user provider](#user-provider), and prefers properties passed explicitly to `fetch()` over provided properties. Also sets the user in the SDK for reuse. | `undefined` |
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +* If your application relies on remote evaluation, but not right at startup, you may set `fetchOnStart` to `false` and call `fetch()` and await the promise separately.
```suggestion
* If your application relies on remote evaluation, but not right at startup, set `fetchOnStart` to `false` and call `fetch()` and await the promise separately.
```

2023-10-10 16:36 UTC, markzegarelli commented on docs/experiment/sdks/react-native-sdk.md
> +Configure the behavior of `start()` by setting `fetchOnStart` in the SDK configuration on initialization to **improve performance based on the needs of your application**.
```suggestion
Set `fetchOnStart` in the SDK configuration to set the behavior of `start()` to improve the performance of your application.
```

2023-10-10 18:58 UTC, bgiori commented on docs/experiment/sdks/react-native-sdk.md
> +        5. [Start the SDK with the user](#fetch)
```suggestion
        5. [Start the SDK with the user](#start)
```

2023-10-10 19:01 UTC, bgiori commented on docs/experiment/sdks/react-native-sdk.md
> +Start the SDK by getting flag configurations from the server and fetching remote evaluation variants for the user. The SDK is ready once the returned promise resolves.
```suggestion
Start the Experiment SDK to get flag configurations from the server and fetch remote evaluation variants for the user. The SDK is ready once the returned promise resolves.
```

2023-10-11 16:02 UTC, markzegarelli approved these changes

2023-10-11 16:30 UTC, merged