Android local evaluation
amplitude/amplitude-dev-center pull request #30
Opened 2023-10-10 15:58 UTC by bgiori

# Amplitude Developer Docs PR

## Description

Local evaluation documentation for android. 

## Deadline

Today

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-10 16:31 UTC, tyiuhc commented on docs/experiment/sdks/android-sdk.md
> +
Missing `source` config

2023-10-10 16:41 UTC, markzegarelli requested changes

2023-10-10 16:41 UTC, markzegarelli commented on docs/experiment/sdks/android-sdk.md
> +The SDK client can be configured once on initialization.
```suggestion
SDK client configuration occurs during initialization.
```

2023-10-10 16:41 UTC, markzegarelli commented on docs/experiment/sdks/android-sdk.md
> +    | `automaticExposureTracking` | If true, calling [`variant()`](#variant) will track an exposure event through the configured `exposureTrackingProvider`. If no exposure tracking provider is set, t
```suggestion
    | `automaticExposureTracking` | If true, calling [`variant()`](#variant) tracks an exposure event through the configured `exposureTrackingProvider`. If no exposure tracking provider is set, this configuration option does nothing.  | `true` |
```

2023-10-10 16:41 UTC, markzegarelli commented on docs/experiment/sdks/android-sdk.md
> +    | `automaticFetchOnAmplitudeIdentityChange` | Only matters if you use the `initializeWithAmplitudeAnalytics` initialization function to seamlessly integrate with the Amplitude Analytics SDK. If `
```suggestion
    | `automaticFetchOnAmplitudeIdentityChange` | Only matters if you use the `initializeWithAmplitudeAnalytics` initialization function to seamlessly integrate with the Amplitude Analytics SDK. If `true` any change to the user ID, device ID or user properties from analytics triggers the experiment SDK to fetch variants and update it's cache. | `false` |
```

2023-10-10 16:41 UTC, markzegarelli commented on docs/experiment/sdks/android-sdk.md
> +    If you're using Amplitude's EU data center, configure the `serverZone` option on initialization to `ServerZone.EU`.
```suggestion
    If you use Amplitude's EU data center, configure the `serverZone` option on initialization to `ServerZone.EU`.
```

2023-10-10 16:41 UTC, markzegarelli commented on docs/experiment/sdks/android-sdk.md
> +Start the SDK by getting flag configurations from the server and fetching remote evaluation variants for the user. The SDK is ready once the returned future resolves.
```suggestion
The Experiment SDK starts when you get flag configurations from the server and fetch remote evaluation variants for the user. The SDK is ready after the returned future resolves.
```

2023-10-10 16:42 UTC, tyiuhc commented on docs/experiment/sdks/android-sdk.md
> +        5. [Start the SDK with the user](#fetch)
should map to `#start`?

2023-10-10 17:58 UTC, bgiori commented on docs/experiment/sdks/android-sdk.md
> +        5. [Start the SDK with the user](#fetch)
```suggestion
        5. [Start the SDK with the user](#start)
```

2023-10-10 18:42 UTC, bgiori commented on docs/experiment/sdks/android-sdk.md
> +Start the SDK by getting flag configurations from the server and fetching remote evaluation variants for the user. The SDK is ready once the returned future resolves.
```suggestion
Start the Experiment SDK to get flag configurations from the server and fetch remote evaluation variants for the user. The SDK is ready once the returned future resolves.
```

2023-10-10 19:03 UTC, tyiuhc commented on docs/experiment/sdks/android-sdk.md
> +    | `source` | The primary source of variants. Set the value to `Source.InitialVariants` and configure `initialVariants` to bootstrap the SDK for SSR or testing purposes. | `Source.LocalStorage` |
`Source.LOCAL_STORAGE` and `Source.INITIAL_VARIANTS`

2023-10-10 19:08 UTC, tyiuhc commented on docs/experiment/sdks/android-sdk.md
> -        ExperimentClient experiment = Experiment.initialize(context, "<DEPLOYMENT_KEY>", config);
do we need to remove angle brackets for `<FLAG_KEY>` as well?

2023-10-10 19:15 UTC, bgiori commented on docs/experiment/sdks/android-sdk.md
> +    | `source` | The primary source of variants. Set the value to `Source.InitialVariants` and configure `initialVariants` to bootstrap the SDK for SSR or testing purposes. | `Source.LocalStorage` |
local storage is the default.

2023-10-11 16:02 UTC, markzegarelli approved these changes

2023-10-11 16:32 UTC, merged