AMP-91621 update Profile API dev doc on multiple computation IDs support
amplitude/amplitude-dev-center pull request #323
Opened 2024-04-29 21:14 UTC by zc632995195

# Amplitude Developer Docs PR
Update Profile API doc that for computation ID we also support it. 

On another path (prediction) it was already mentioned we supported it: https://www.docs.developers.amplitude.com/analytics/apis/user-profile-api/#get-singlemultiple-prediction-propensity --> thus for this I copy the section data to explain how multiple computations are supported. 

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-04-29 22:12 UTC, markzegarelli requested changes

2024-04-29 22:12 UTC, markzegarelli commented on docs/analytics/apis/user-profile-api.md
> +Retrieves a single or multiple computation by ID(s). Find the computation ID by navigating to the computation in the Audiences web app and copying the ID at the end of the URL. The ID is bold in this
```suggestion
Retrieves a single or multiple computation by ID. Navigate to the computation in Audiences to find and copy the ID at the end of the URL. For example, `t14bqib` is the ID in  `https://app.amplitude.com/audiences/org_name_00000/computations/t14bqib/`
```

2024-05-02 23:07 UTC, markzegarelli approved these changes

2024-05-02 23:25 UTC, zc632995195 commented
um why is there a change in webhook streaming file: docs/data/destinations/webhooks-streaming.md. 

This PR is meant for `docs/analytics/apis/user-profile-api.md` only, let me rebase/clean up bit...

2024-05-02 23:28 UTC, markzegarelli commented
> um why is there a change in webhook streaming file: docs/data/destinations/webhooks-streaming.md.
> 
> This PR is meant for `docs/analytics/apis/user-profile-api.md` only, let me rebase/clean up bit...

My mistake! I must have neglected to check my changed files on the branch. Sorry!

2024-05-02 23:34 UTC, merged