Update humanic-ai-cohort.md
amplitude/amplitude-dev-center pull request #340
Opened 2024-05-11 17:36 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-05-11 17:37 UTC, Brandoncharleskhoo1 commented
![Screenshot 2024-05-11 at 10 37 01 AM](https://github.com/amplitude/amplitude-dev-center/assets/76189397/9bba8eec-2291-4b21-8895-f94629ccdce4)

2024-05-13 16:30 UTC, markzegarelli requested changes

2024-05-13 16:30 UTC, markzegarelli commented on docs/data/destinations/humanic-ai-cohort.md
> +    This integration is maintained by Humanic AI. Email **care@humanic.ai** for support with this integration. 
```suggestion
    This integration is maintained by Humanic AI. Email [care@humanic.ai](mailto:care@humanic.ai) for support with this integration. 
```

2024-05-18 00:56 UTC, Brandoncharleskhoo1 commented
HI @markzegarelli i already implemented your suggestion so not sure why merging is still blocked

2024-05-21 16:22 UTC, markzegarelli approved these changes

2024-05-21 16:23 UTC, markzegarelli commented
@Brandoncharleskhoo1 My bad, should be good to go now.

2024-05-24 21:11 UTC, merged

2024-06-08 01:20 UTC, arjunsaksena1 commented
Hi Team, 

Two changes are required: 

1. The first line needs to say "Humanic is an Agentic Marketing Platform that helps you unlock growth by using AI agents"
2. Humanic is free to use so we need to delete the second line under Considerations "You need to have a paid Humanic.ai plan to enable this integration."

Thank you!