Update braze-cohort.md
amplitude/amplitude-dev-center pull request #346
Opened 2024-05-16 07:58 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-05-16 16:00 UTC, markzegarelli requested changes

2024-05-16 16:00 UTC, markzegarelli commented on docs/data/destinations/braze-cohort.md
> +??? note "Why can't I see the list of users in Braze?"
```suggestion
### Why can't I see the list of users in Braze?
```

2024-05-16 16:00 UTC, markzegarelli commented on docs/data/destinations/braze-cohort.md
> +### Frequently asked questions
```suggestion
## Frequently asked questions
```

2024-05-16 16:00 UTC, markzegarelli commented on docs/data/destinations/braze-cohort.md
> +    One common issue is that the users in the Amplitude cohort may not exist in Braze. When you sync to Braze, new users will not be created if they do not already exist in Braze. Therefore, it's imp
```suggestion
When you sync a cohort, Braze matches users in that cohort with users that already exist in Braze, and doesn't create new users. Make sure users in your Amplitude cohort have a matching user (`userId`) in Braze.
```

2024-05-16 16:20 UTC, markzegarelli commented on docs/data/destinations/braze-cohort.md
> +
```suggestion
```

2024-05-18 00:56 UTC, Brandoncharleskhoo1 commented
@markzegarelli Hi Mark, i'm not sure what else I have to do here. I already committed your suggestions :)

2024-06-25 21:54 UTC, markzegarelli commented
Moved to new site

2024-06-25 21:54 UTC, closed without merging