AMP-96489 Add new docs for lookup table apis v3
amplitude/amplitude-dev-center pull request #349
Opened 2024-05-20 16:38 UTC by rctbusk

# Amplitude Developer Docs PR

## Description
Added docs for the new Lookup Table API V3, which is under data-api, so moved to the Data section.

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [X] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [ X ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-05-21 02:34 UTC, shibrady commented on docs/data/sources/lookup-table.md
> +3. Select column in CSV to map property to.
Grammar seems a bit off?

2024-05-23 18:15 UTC, rctbusk commented on docs/analytics/apis/lookup-tables-api.md
> +    This API is no longer supported. Use the new [API](/data/sources/lookup-table).
Yep, will fix :)

2024-05-23 18:19 UTC, rctbusk commented on docs/data/sources/lookup-table.md
> +3. Select column in CSV to map property to.
Tried fixing a bit

2024-05-23 18:19 UTC, rctbusk commented on docs/analytics/apis/lookup-tables-api.md
> +    This API is no longer supported. Use the new [API](/data/sources/lookup-table).
Fixed

2024-05-23 20:17 UTC, shibrady approved these changes

2024-05-23 20:17 UTC, shibrady commented on docs/data/apis/lookup-tables-api.md
> +- If a field value contains commas or quotes, it should be wrapped within double quotation marks. The first double quote signifies the beginning of the column data, and the last double quote marks th
Verbiage is inconsistent - let's just call these double quotes?

2024-05-23 20:17 UTC, shibrady commented on docs/data/apis/lookup-tables-api.md
> +title: Lookup Table API
Casing seems inconsistent throughout the doc when it comes to lookup tables - when should and shouldn't "Lookup Table" be capitalized?

e.g. Header sections don't seem like they're title cased until Lookup Tables are involved

You can "Delete a Lookup Table", but "To create a lookup property, create a lookup table", etc.

2024-05-23 20:17 UTC, shibrady commented on docs/data/sources/lookup-table.md
> +3. Select column in CSV as the key column.
Maybe "Select a column in the CSV to be the key column"?

2024-05-28 19:58 UTC, markzegarelli requested changes

2024-05-28 19:58 UTC, markzegarelli commented on docs/data/sources/lookup-table.md
> +    - If a field value contains commas or quotes, it should be wrapped within double quotation marks. The first double quote signifies the beginning of the column data, and the last double quote mark
```suggestion
    - If a field value contains commas or quotes, wrap the contents with double quotation marks (`"`). The first double quote signifies the beginning of the column data, and the last double quote marks the end. If the value contains a string with double quotes, these are replaced by double quotes.
```
@rctbusk I'm not clear on the last sentence here. It seems like we should tell users to replace double-quotes within a field with single quotes, so they don't interfere with the double-quote wrapper. Is this accurate?

2024-05-28 20:01 UTC, rctbusk commented on docs/data/sources/lookup-table.md
> +    - If a field value contains commas or quotes, it should be wrapped within double quotation marks. The first double quote signifies the beginning of the column data, and the last double quote mark
yep! that makes sense.

2024-05-29 16:10 UTC, markzegarelli commented on docs/data/sources/lookup-table.md
> +    - If a field value contains commas or quotes, wrap the contents with double quotation marks (`"`). The first double quote signifies the beginning of the column data, and the last double quote mar
```suggestion
    - If a field value contains commas or quotes, wrap the contents with double quotation marks (`"`). The first double quote signifies the beginning of the column data, and the last double quote marks the end. If a string contains double quotes, replace them with single quotes.
```

2024-05-29 18:14 UTC, merged