AMP-100504 - Browser SDK supports getting session id from URL
amplitude/amplitude-dev-center pull request #350
Opened 2024-05-20 23:52 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

[AMP-100504]

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2024-05-22 16:29 UTC, markzegarelli requested changes

2024-05-22 21:13 UTC, markzegarelli approved these changes

2024-05-23 20:11 UTC, justin-fiedler commented on docs/data/sources/google-tag-manager-client.md
> +To retain user identification across domains, create a custom HTML tag to attach the user's `deviceId` to the domain link you wish to track. When you append `ampDeviceId=YourDeviceId` to the URL, the
```suggestion
To retain user identification across domains, create a custom HTML tag to attach the user's `deviceId` to the domain link you wish to track. When you append `ampDeviceId=YourDeviceId` to the URL, the Amplitude Browser SDK uses the URL parameter value rather than generate a new `deviceId`. For more information see an [example script](https://github.com/amplitude/GTM-cross-domain-script) on GitHub.
```

2024-05-23 20:11 UTC, justin-fiedler commented on includes/sdk-ts-browser/shared-cross-domain-tracking.md
> +    - Takes `ampDeviceId` URL parameter as the first option for device ID and falls back to `deviceId` URL parameter for backward compatitible. So you don't need to change your code to upgrade to ver
I think it would be good to structure the multiple options similarly. e.g. make it similar to the session ID option above.

```suggestion
    - Supports getting the  device ID from the URL paramter `ampDeviceId`. The URL parameter takes precedence over the SDK configuration. Previous versions of the SDK supported the `deviceId` URL parameter, this option is still supported for backward compatibility but `ampDeviceId` will take precedence if both are set. You don't need to change your code if upgrade to versions higher than `v2.8.0` but it is recommended.
```

2024-05-23 20:11 UTC, justin-fiedler approved these changes

2024-05-23 20:48 UTC, yuhao900914 approved these changes

2024-05-23 20:48 UTC, yuhao900914 commented on includes/sdk-ts-browser/shared-cross-domain-tracking.md
> +// https://www.example.com?ampDeviceId=my-device-id&ampSessionId=12345
Might be replace the ampSessionId with a real timestamp?

2024-05-23 20:48 UTC, yuhao900914 commented on docs/data/sources/google-tag-manager-client.md
> +Starting from template version `15cce` (library version `amplitude-ts-gtm/3.7.12`), the template supports getting the session ID from the URL parameter `ampSessionId` to maintain the same session. Fo
nits: Could we change to Browser SDK 2.0

2024-05-23 21:58 UTC, Mercy811 commented on includes/sdk-ts-browser/shared-cross-domain-tracking.md
> +    - Takes `ampDeviceId` URL parameter as the first option for device ID and falls back to `deviceId` URL parameter for backward compatitible. So you don't need to change your code to upgrade to ver
Thanks Justin, it looks better. But SDK configuration takes precedence over the URL parameter. I changed it to 
```
Starting from `v2.8.0` the SDK supports getting the device ID from the URL paramter `ampDeviceId`. The SDK configuration, for example, `init('API_KEY', { deviceId: 'custom-device-id' })` still takes precedence over the URL parameter. Previous versions of the SDK supported the `deviceId` URL parameter, this option is still supported for backward compatibility but `ampDeviceId` will take precedence if both are set. You don't need to change your code if upgrade to versions higher than `v2.8.0` but it is recommended.
```

2024-05-23 21:58 UTC, Mercy811 commented on includes/sdk-ts-browser/shared-cross-domain-tracking.md
> +// https://www.example.com?ampDeviceId=my-device-id&ampSessionId=12345
This is an example of not using a real timestamp will cause a problem.

2024-05-23 22:02 UTC, Mercy811 commented on docs/data/sources/google-tag-manager-client.md
> +Starting from template version `15cce` (library version `amplitude-ts-gtm/3.7.12`), the template supports getting the session ID from the URL parameter `ampSessionId` to maintain the same session. Fo
Updated at https://github.com/amplitude/amplitude-dev-center/pull/350/commits/24b5ab67fbdef7a40d49b66d4dfc6693b0da9140

2024-05-23 22:16 UTC, merged