Create liveramp-cohort.md
amplitude/amplitude-dev-center pull request #36
Opened 2023-10-18 10:06 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-18 17:21 UTC, markzegarelli requested changes

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +## Setup
```suggestion
```
I don't think we need this heading here.

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +### Send cohort via Secure File Transfer Protocol (SFTP)
```suggestion
## Send a cohort through Secure File Transfer Protocol (SFTP) 

To send a cohort from Amplitude to LiveRamp through SFTP:
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +1. **Create Cohort in Amplitude:** Start by creating the cohort you want to sync in Amplitude.
```suggestion
1. **Create the Cohort in Amplitude:** If the cohort you want to send does not exist, create it in Amplitude.
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +2. **Export Cohort from Amplitude:** Export the cohort as a CSV file or via the Behavioral Cohorts API. See this [document](https://help.amplitude.com/hc/en-us/articles/360028552471-Amplitude-Audienc
```suggestion
2. **Export the Cohort from Amplitude:** Export the cohort as a CSV file or with the Behavioral Cohorts API. See this [document](https://help.amplitude.com/hc/en-us/articles/360028552471-Amplitude-Audiences-overview-Drive-conversions-with-true-one-to-one-personalization-) for more details.
```

What details should users look for in the linked article? We should point directly to content about CSV export or the Behavioral Cohorts API.

Also, please use the article title as the link text, instead of `document`. For example:

`For more information, see [Article title | Article section](url)`

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +3. **Upload Cohort to SFTP Server:** Securely upload the exported cohort file to your SFTP server. Refer to your [SFTP server documentation](https://docs.liveramp.com/connect/en/upload-a-file-via-liv
```suggestion
3. **Upload the Cohort to SFTP Server:** Upload the exported cohort file to LiveRamp's SFTP server. See LiveRamp's article [Upload a File via LiveRamp's SFTP](https://docs.liveramp.com/connect/en/upload-a-file-via-liveramp-s-sftp.html) for more information. LiveRamp may take up to 3 days to ingest your cohort data from the SFTP location.
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +    - Liveramp can take up to 1-3 days to ingest the data from SFTP into Liveramp.
```suggestion
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +4. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (e.g., Facebook Ads) for cohort activation.
Is there LiveRamp documentation we can point to for these last two steps? Documenting LiveRamp features in our docs is not ideal.

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +### Send cohort via Amazon S3
```suggestion
### Send a cohort with Amazon S3

To send a cohort from Amplitude to LiveRamp through an Amazon S3 bucket:
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +1. **Create Cohort in Amplitude:** Create the desired cohort within Amplitude.
```suggestion

1. **Create the Cohort in Amplitude:** If the cohort you want to send does not exist, create it in Amplitude.
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +2. **Set Up Amazon S3 Bucket:** Configure your Amazon S3 bucket if you don't have one already, using the AWS Management Console.
```suggestion
2. **Configure the Amazon S3 Bucket:** Use the AWS Management Console to create an S3 bucket, if you don't have one.
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +3. **Send Cohort to Amazon S3:** Use the [Amazon S3 cohort sync](https://www.docs.developers.amplitude.com/data/destinations/amazon-s3-cohort/) integration to sync cohort data from Amplitude to your
```suggestion
3. **Send the Cohort to Amazon S3:** Use the [Amazon S3 cohort sync](https://www.docs.developers.amplitude.com/data/destinations/amazon-s3-cohort/) integration to sync cohort data from Amplitude to your Amazon S3 bucket.
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +4. **Log Into LiveRamp:** Access your LiveRamp account.
Does LiveRamp have documentation about how to retrieve the cohort data from S3?

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +## Send cohort via Snowflake
```suggestion
## Send a cohort with Snowflake

To send a cohort from Amplitude to LiveRamp with Snowflake:
```

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +1. **Send Cohorts to Amazon S3:** Send cohorts from Amplitude to Amazon S3. See this document for more details.
What document?

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +2. **Bulk Loading from Amazon S3:** Load cohort data from your Amazon S3 bucket into your Snowflake data warehouse. See this document for more details.
```suggestion
2. **Bulk Load from Amazon S3:** Load cohort data from your Amazon S3 bucket into your Snowflake data warehouse. See this document for more details.
```

What document?

2023-10-18 17:21 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +3. **Install LiveRamp Native Application on Snowflake:** Install the LiveRamp native application in your Snowflake environment.
Again, we should link to LiveRamp documentation here, so we are responsible for updates if instructions change on their side.

2023-10-18 21:53 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/liveramp-cohort.md
> +3. **Install LiveRamp Native Application on Snowflake:** Install the LiveRamp native application in your Snowflake environment.
Updated the link.

2023-10-18 21:53 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/liveramp-cohort.md
> +1. **Send Cohorts to Amazon S3:** Send cohorts from Amplitude to Amazon S3. See this document for more details.
Updated the link.

2023-10-18 21:53 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/liveramp-cohort.md
> +4. **Log Into LiveRamp:** Access your LiveRamp account.
Updated the link.

2023-10-18 22:01 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/liveramp-cohort.md
> +4. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (e.g., Facebook Ads) for cohort activation.
Agreed! I forgot to add the link. I originally had a google doc where I created the draft.

2023-10-18 22:02 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/liveramp-cohort.md
> +This guide is your resource for sending cohorts from Amplitude to LiveRamp, a powerful data connectivity platform. By following the instructions outlined here, you can seamlessly synchronize and acti
Updated it and made it more brief :)

2023-10-18 22:23 UTC, markzegarelli requested changes
A few more comments.

In general, when you add a link, please add the article's title as the link text, and not `[document]`. Also, where applicable, add if it's a partner's article.

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +- A paid LiveRamp license is required for this integration.
```suggestion
A paid LiveRamp license is required for this integration.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +4. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (e.g., Facebook Ads) for cohort activation.
```suggestion
4. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (for example, Facebook Ads) for cohort activation.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +1. **Create the Cohort in Amplitude:** If the cohort you want to send does not exist, create it in Amplitude.
```suggestion
1. **Create the Cohort in Amplitude:** If the cohort you want to send doesn't exist, create it in Amplitude.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +4. **Grant Liveramp access to your Amazon S3 bucket:** Allow LiveRamp to Access Your AWS S3 Bucket. See this [document](https://docs.liveramp.com/connect/en/allow-liveramp-to-access-your-aws-s3-bucke
```suggestion
4. **Grant LiveRamp access to your Amazon S3 bucket:** Allow LiveRamp to Access Your AWS S3 Bucket. For more information, see LiveRamp's article, [Allow LiveRamp to Access your AWS S3 Bucket](https://docs.liveramp.com/connect/en/allow-liveramp-to-access-your-aws-s3-bucket.html)
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +7. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (e.g., Facebook Ads) for cohort activation.
```suggestion
7. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (for example, Facebook Ads) for cohort activation.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +8. **Add Cohort to Destination:** Add the cohort to the chosen destination account within LiveRamp to activate it.
```suggestion
8. **Add Cohort to Destination:** Add the cohort to the chosen destination account in LiveRamp to activate it.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +6. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (e.g., Facebook Ads) for cohort activation.
```suggestion
6. **Choose Destination Account:** In LiveRamp, select a destination account based on your media plan (for example, Facebook Ads) for cohort activation.
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +1. **Send Cohorts to Amazon S3:** Send cohorts from Amplitude to Amazon S3. See this [document](https://www.docs.developers.amplitude.com/data/destinations/amazon-s3-cohort/) for more details.
```suggestion
1. **Send Cohorts to Amazon S3:** Send cohorts from Amplitude to Amazon S3. For more information, see [Send Cohorts to Amazon S3](https://www.docs.developers.amplitude.com/data/destinations/amazon-s3-cohort/)
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +2. **Bulk Load from Amazon S3:** Load cohort data from your Amazon S3 bucket into your Snowflake data warehouse. See this [document](https://docs.snowflake.com/en/user-guide/data-load-s3) for more de
```suggestion
2. **Bulk Load from Amazon S3:** Load cohort data from your Amazon S3 bucket into your Snowflake data warehouse. For more information, see Snowflake's article, [Bulk Loading from Amazon S3](https://docs.snowflake.com/en/user-guide/data-load-s3).
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +3. **Install LiveRamp Native Application on Snowflake:** Install the LiveRamp native application in your Snowflake environment. See this [document](https://docs.liveramp.com/identity/en/set-up-the-li
```suggestion
3. **Install LiveRamp Native Application on Snowflake:** Install the LiveRamp native application in your Snowflake environment. For more information, see LiveRamp's article, [Set Up the LiveRamp Native App in Snowflake](https://docs.liveramp.com/identity/en/set-up-the-liveramp-native-app-in-snowflake.html).
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +4. **Enable LiveRamp Embedded Identity in Snowflake:** Activate LiveRamp's Identity Resolution in Snowflake to translate identifiers to RampIDs. See this [document](https://docs.liveramp.com/identity
```suggestion
4. **Enable LiveRamp Embedded Identity in Snowflake:** Activate LiveRamp's Identity Resolution in Snowflake to translate identifiers to RampIDs. For more information, see LiveRamp's article [Perform Identity Resolution in Snowflake](https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html).
```

2023-10-18 22:23 UTC, markzegarelli commented on docs/data/destinations/liveramp-cohort.md
> +5. **Share Data to LiveRamp Account:** Share the processed data with your LiveRamp account.
How should a user do this? This step doesn't provide any instruction as written.

2023-10-19 16:23 UTC, markzegarelli approved these changes

2023-10-19 18:01 UTC, merged