SKY-3483 update props syntax
amplitude/amplitude-dev-center pull request #40
Opened 2023-10-20 22:33 UTC by imousterian

# Amplitude Developer Docs PR

## Description

Update documentation for MGT API. [SKY-3483](https://amplitude.atlassian.net/browse/SKY-3483)

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [x] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-20 22:56 UTC, markzegarelli requested changes

2023-10-20 22:56 UTC, markzegarelli commented on docs/experiment/apis/management-api/api-beta.md
> +|`prop`| Required | string | The property to use in the condition. Custom and free-form properties must be prefixed with `gp:` |
```suggestion
|`prop`| Required | string | The property to use in the condition. Prefix custom and free-form properties with  `gp:` |
```

2023-10-20 22:56 UTC, markzegarelli commented on docs/experiment/apis/management-api/experiments.md
> +|`prop`| Required | string | The property to use in the condition. Custom and free-form properties must be prefixed with `gp:` |
```suggestion
|`prop`| Required | string | The property to use in the condition. Prefix custom and free-form properties with  `gp:` |
```

2023-10-20 22:56 UTC, markzegarelli commented on docs/experiment/apis/management-api/flags.md
> +|`prop`| Required | string | The property to use in the condition. Custom and free-form properties must be prefixed with `gp:` |
```suggestion
|`prop`| Required | string | The property to use in the condition. Prefix custom and free-form properties with  `gp:` |
```

2023-10-21 01:06 UTC, bgiori approved these changes

2023-10-23 16:13 UTC, markzegarelli approved these changes

2023-10-23 16:43 UTC, merged