Update with Experiment PHP Server SDK remote evaluation docs
amplitude/amplitude-dev-center pull request #43
Opened 2023-10-23 18:56 UTC by tyiuhc

# Amplitude Developer Docs PR

## Description

Update with Experiment PHP Server SDK remote evaluation docs

## Deadline

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [X] Doc update.
- [X] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [X] I previewed my documentation on a local server using `mkdocs serve`.
- [X] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-10-23 21:01 UTC, markzegarelli requested changes

2023-10-23 21:01 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +    | `fetchRetryBackoffMaxMillis` | The maximum backoff between retries. If the scaled backoff becomes greater than the max, the max is used for all subsequent requests | `10000` |
```suggestion
    | `fetchRetryBackoffMaxMillis` | The maximum backoff between retries. If the scaled backoff becomes greater than the maximum, Experiment uses the  maximum for all subsequent requests. | `10000` |
```

2023-10-23 21:01 UTC, markzegarelli commented on docs/experiment/sdks/php-sdk.md
> +    If you're using Amplitude's EU data center, configure the `serverUrl` option on initialization to `https://api.lab.eu.amplitude.com`
```suggestion
    If you use Amplitude's EU data center, set the `serverUrl` option on initialization to `https://api.lab.eu.amplitude.com`
```

2023-10-23 21:40 UTC, markzegarelli approved these changes

2023-10-24 16:40 UTC, bgiori approved these changes
🥇

2023-10-24 16:40 UTC, bgiori commented on docs/experiment/sdks/php-sdk.md
> +!!!note
```suggestion
```

2023-10-24 16:40 UTC, bgiori commented on docs/experiment/sdks/php-sdk.md
> +!!!info "SDK Resources"
```suggestion
!!!beta "SDK Resources"
```

2023-10-24 16:40 UTC, bgiori commented on docs/experiment/sdks/php-sdk.md
> +title: Experiment PHP SDK
```suggestion
title: Experiment PHP SDK (Beta)
```

2023-10-24 16:40 UTC, bgiori commented on docs/experiment/sdks/php-sdk.md
> +    | `fetchRetryBackoffMinMillis` | The minimum (initial) backoff after a request to fetch variants fails. This delay scales according to the the `fetchRetryBackoffScalar` setting. | `500` |
```suggestion
    | `fetchRetryBackoffMinMillis` | The minimum (initial) backoff after a request to fetch variants fails. This delay scales according to the `fetchRetryBackoffScalar` setting. | `500` |
```

2023-10-24 21:00 UTC, merged