fix: add min id length admonition
amplitude/amplitude-dev-center pull request #53
Opened 2023-11-02 21:35 UTC by Mercy811

# Amplitude Developer Docs PR

## Description

`api2.amplitude.com` have no min length requirements for device IDs and user IDs but http v2 api has mim id length to be 5. Emphasize the need to match the user ID's default length to prevent similar [issue](https://amplitude.atlassian.net/browse/AMP-87192) for customers.

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-02 21:45 UTC, markzegarelli requested changes

2023-11-02 21:45 UTC, markzegarelli commented on docs/data/sdks/ios-swift/migration.md
> +|Have no length limit on deviceId or userId.|`config.minIdLength`overwrites the minimum length deviceId and userId.|
```suggestion
| `deviceId` and `userId` don't have a minimum length.|`config.minIdLength` overwrites the minimum length `deviceId` and `userId`.|
```

@Mercy811 So is the minimum for Amplitude-Swift 5, which you can override with `config.minIdLength`?

2023-11-02 21:45 UTC, markzegarelli commented on includes/sdk-min-id-length.md
> +    The maintenance SDK uses the old SDK endpoint (`api2.amplitude.com`) which has no length limit on device Id and user Id. But the latest SDK uses HTTP V2 API (`api2.amplitude.com/2/httpapi`) which
```suggestion
    The maintenance SDK uses an old SDK endpoint (`api2.amplitude.com`) which enforces no length limit for `deviceId` and `userId`. The latest SDK uses Amplitude's HTTP V2 API (`api2.amplitude.com/2/httpapi`) and requires identifiers to be at least 5 characters by default. When you migrate to the new SDK, set `config.minIdLength` to a smaller value if you allowed identifiers with fewer than 5 characters.
```

2023-11-02 22:08 UTC, Mercy811 commented on docs/data/sdks/ios-swift/migration.md
> +|Have no length limit on deviceId or userId.|`config.minIdLength`overwrites the minimum length deviceId and userId.|
Yes!

2023-11-02 22:48 UTC, markzegarelli commented on docs/data/sdks/ios-swift/migration.md
> +| `deviceId` and `userId` don't have a minimum length.|`config.minIdLength` overwrites the minimum length `deviceId` and `userId`.|
```suggestion
| `deviceId` and `userId` don't have a minimum length.| Minimum length is 5. `config.minIdLength` overwrites the minimum length  of`deviceId` and `userId`.|
```

2023-11-02 22:48 UTC, markzegarelli approved these changes

2023-11-03 17:16 UTC, justin-fiedler approved these changes
Thanks @Mercy811!

2023-11-03 17:45 UTC, merged