Create sleekflow.md
amplitude/amplitude-dev-center pull request #55
Opened 2023-11-04 03:34 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-06 18:05 UTC, markzegarelli requested changes
@Brandoncharleskhoo1 Can you share a screenshot of the UI from Sleekflow? I think there is a better way to document it, but need to see what it looks like first.

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +2. Click on **Create new rule**.
```suggestion
2. Click **Create new rule**.
```

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +3. Click **Customized a rule**.
Customize a rule? Customized rule?

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +1. In Sleekflow, click on the **Automation** tab.
```suggestion
1. In Sleekflow, navigate to the **Automation** tab.
```

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +4. Click on **Incoming messages**.
```suggestion
4. Click **Incoming messages**.
```

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +10. In the blank, fill in: https://sleekflow-amplitude-f375paklaq-uc.a.run.app/receive-message?apiKey={api_key}.
Where does a user find this API key? Amplitude? Sleekflow?

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +1. **User Behavior Analysis:** You can track how users engage with your brand or business through different messaging platforms. This includes monitoring when users open messages, click on links, mak
```suggestion
1. **User Behavior Analysis:** Track how users engage with your brand or business through different messaging platforms. Monitor when users open messages, click links, make inquiries, or complete transactions. This data helps you understand user behavior and preferences.
```

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +2. **Conversion Tracking:** By sending events related to conversions (e.g., completing a purchase, signing up for a newsletter, or requesting more information) to Amplitude, you can measure the effec
```suggestion
2. **Conversion Tracking:** When you send events related to conversions (like completing a purchase, signing up for a newsletter, or requesting more information) to Amplitude, you can measure the effectiveness of your messaging campaigns on different platforms. This information can help you optimize your marketing strategies.
```

2023-11-06 18:05 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +3. **User Segmentation:** Amplitude allows you to create user segments based on specific actions and behaviors. You can use Sleekflow's event data to create custom segments of users who have interact
```suggestion
3. **User Segmentation:** Amplitude allows you to create user segments based on specific actions and behaviors. Use Sleekflow's event data to create custom segments of users who've interacted with your business in particular ways on different channels. Use this segmentation for targeted messaging and marketing efforts.
```

2023-11-21 20:41 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +12. In the same blank as step 9, fill in: https://sleekflow-amplitude-f375paklaq-uc.a.run.app/send-message?apiKey={api_key}.
@Brandoncharleskhoo1 Can you clarify this one?

2023-11-21 20:41 UTC, markzegarelli commented on docs/data/sources/sleekflow.md
> +10. In the blank, fill in: https://sleekflow-amplitude-f375paklaq-uc.a.run.app/receive-message?apiKey={api_key}.
@Brandoncharleskhoo1 Can you clarify this one?

2023-11-29 22:59 UTC, Brandoncharleskhoo1 commented on docs/data/sources/sleekflow.md
> +12. In the same blank as step 9, fill in: https://sleekflow-amplitude-f375paklaq-uc.a.run.app/send-message?apiKey={api_key}.
@jamesbrandon @isaacli430 Are you able to clarify the steps here?

2023-11-29 22:59 UTC, Brandoncharleskhoo1 commented on docs/data/sources/sleekflow.md
> +3. Click **Customized a rule**.
@jamesbrandon @isaacli430 Are you able to clarify the steps here as well?

2023-11-29 22:59 UTC, Brandoncharleskhoo1 commented on docs/data/sources/sleekflow.md
> +10. In the blank, fill in: https://sleekflow-amplitude-f375paklaq-uc.a.run.app/receive-message?apiKey={api_key}.
@jamesbrandon @isaacli430 Are you able to clarify the steps here as well?

2024-02-13 06:33 UTC, closed without merging