Update aliasing-api.md to reflect new GET endpoint
amplitude/amplitude-dev-center pull request #67
Opened 2023-11-10 01:00 UTC by robynnason

We have added a new GET api for user mappings. See: https://amplitude.atlassian.net/jira/software/c/projects/AMP/boards/86?assignee=60073f9074c3e200715d3d64&selectedIssue=AMP-86909 

Adding it into the documentation so customers may use it.

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-10 01:01 UTC, nwangtw approved these changes

2023-11-10 18:44 UTC, markzegarelli requested changes

2023-11-10 18:44 UTC, markzegarelli commented on docs/analytics/apis/aliasing-api.md
> +| `mappings`                         | The mappings associated with this user id. See next section.  Empty if the requested user isn't found     |
```suggestion
| `mappings`                         | The mappings associated with this user id. See next section. Empty if the requested user isn't found     |
```

2023-11-10 18:44 UTC, markzegarelli commented on docs/analytics/apis/aliasing-api.md
> +
```suggestion
```

2023-11-10 18:44 UTC, markzegarelli commented on docs/analytics/apis/aliasing-api.md
> +NOTE: This is a different url, https://amplitude.com/api/2/usermap, than the map and unmap endpoints above.
```suggestion
!!! info
    User mappings uses a different URL than the map and unmap endpoints above, `https://amplitude.com/api/2/usermap`.
```

2023-11-10 18:44 UTC, markzegarelli commented on docs/analytics/apis/aliasing-api.md
> +```python
```suggestion

```python
```

2023-11-13 18:40 UTC, markzegarelli approved these changes

2023-11-13 18:40 UTC, merged