Update google-ads-event-streaming.md
amplitude/amplitude-dev-center pull request #72
Opened 2023-11-14 20:38 UTC by zheniasemenina

Linked the credentials we require to Google's documentation to simplify locating those; added the 'Common issues' section for self-serve troubleshooting purposes

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-14 21:51 UTC, markzegarelli requested changes
@zheniasemenina Great work!

I've left some suggestions, which you can address directly in the GitHub web viewer. Let me know if you have any questions about that, or questions about my feedback in general

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +## Common Issues
```suggestion
## Common issues
```

For headings, we use sentence style capitalization.

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +You might see the `ERR_BLOCKED_BY_CLIENT` error in your console, which is a common case when AdBlock is installed.
```suggestion
If you see `ERR_BLOCKED_BY_CLIENT` in your browser's console, ensure that your ad blocker is disabled, clear your browser's cache and cookies, and try to add the connection again.
```
Reworded this a bit to remove the passive voice "is installed" and remove the word "please". In general, we want to write from the point of view that we tell users what to do, not ask them to do something.

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +Please remove any browser extensions, clear your cache and cookies, and try to re-add the connection.
```suggestion
```
See above

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +You can learn more about your **Google Ads Customer ID** in [this article](https://support.google.com/google-ads/answer/1704344?hl=en)
```suggestion
Google Ads requires a **Customer ID** to configure as an integration with Amplitude. For more information, see [Find your Google Ads customer ID](https://support.google.com/google-ads/answer/1704344?hl=en) in Google's documentation.
```

Change passive voice (is required) to active voice (requires). 

As a best practice when you link to other documentation, include the article name in the link text, and give the user an indication of where they are going, in this case "Google's documentation."

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +A **Customer ID** is required to set up Google Ads.
```suggestion
```
Combined with next paragraph.

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +- **Manager Account Customer ID** is different from the **Customer ID**.
```suggestion
Keep in mind, **Manager Account Customer ID** is different from the **Customer ID**.
```
Lists with a single bullet don't need to be a list.

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +Check if you have a Google Ads Manager account and you are an Admin.
```suggestion
Amplitude's Google Ads Event Streaming integration requires that your Google Ads Manager account has administrator privileges. This level of permission allows Amplitude to add and remove users from specific user lists in Google Ads.
```
Avoid referring to Amplitude as "we." This can be especially confusing in documentation that covers a third-party integration like this, as the user may not know who "we" is.

2023-11-14 21:51 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +You can learn more about it [here](https://support.google.com/google-ads/answer/9978556)
```suggestion
For more information, see [About access levels in your Google Ads Account
](https://support.google.com/google-ads/answer/9978556) in Google's documentation. 
```

2023-11-17 13:34 UTC, zheniasemenina reviewed
Final v

2023-11-17 18:37 UTC, markzegarelli requested changes
A few more small ones.

2023-11-17 18:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +In the case of Google Ads, we add and remove users from a specific user list. As such, we need appropriate permissions to create and delete Google Ads account data.
```suggestion
For Google Ads, Amplitude adds and removes users from a specific user list. As a result, Amplitude needs appropriate permissions to create and delete Google Ads account data.
```

2023-11-17 18:37 UTC, markzegarelli commented on docs/data/destinations/google-ads-event-streaming.md
> +If you see `ERR_BLOCKED_BY_CLIENT` in your browser's console, ensure that your ad blocker is disabled, clear your browser's cache and cookies, and try to add the connection again.
```suggestion
If you see `ERR_BLOCKED_BY_CLIENT` in your browser's console, disable your ad blocker, clear your browser's cache and cookies, and try to add the connection again.
```

2023-11-20 17:07 UTC, markzegarelli approved these changes

2023-11-20 17:08 UTC, merged