Update google-ads.md
amplitude/amplitude-dev-center pull request #73
Opened 2023-11-15 14:41 UTC by zheniasemenina

Added two new sections: 'Considerations' and 'Common issues'.

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-15 22:55 UTC, markzegarelli requested changes

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +1. Check if you reject unplanned events in your [Schema settings](https://help.amplitude.com/hc/en-us/articles/360055495852-Configure-the-Schema-settings-to-handle-unexpected-data). If you reject unp
```suggestion
1. Check if you reject unplanned events in your [Schema settings](https://help.amplitude.com/hc/en-us/articles/360055495852-Configure-the-Schema-settings-to-handle-unexpected-data). If you reject unplanned data,  Amplitude doesn't store the event or its properties.
```

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +You can learn more about handling unplanned event types in this article.
Which article?

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +2. Do your users have corresponding accounts in Amplitude and Google Ads? Google Ads import will try to match users between platforms based on the key-value pairs you selected, so your import job wil
```suggestion
2. Do your users have corresponding accounts in Amplitude and Google Ads? Google Ads import tries to match users between platforms based on the key-value pairs you selected. If your import job doesn't find any corresponding values, it fails.
```

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +### Import job ingests no data
I think we can remove the numbered list here, and either:

- Use a bulleted list and write an introductory sentence
- Just write the content in paragraph form

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +### Daily Ad Metric discrepancies
```suggestion
### Daily ad metric discrepancies 
```

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +Your metrics may occasionally update days after a click occurs. This can happen for a number of reasons, including but not limited to:
```suggestion
Your metrics may occasionally update days after a click occurs. This can happen for many  reasons, including but not limited to:
```

2023-11-15 22:55 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +Hence, if Google updates the data afterward - the import job will have to run again to get the updated numbers.
Here, do you mean that if:

1. A user clicks a button
2. Data syncs to Google Ads
3. The user converts

The conversion won't show in Google Ads until the next sync?

2023-11-17 13:39 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +- The advertising data you import will be associated with the new Amplitude event called `Daily Ad Metrics` with several event properties, such as `Ad Impressions`, `Ad Clicks`, `Ad Group ID`, etc. F
What if I'm not listing all the items and want to indicate that there are more associated with this event?

2023-11-17 13:55 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +You can learn more about handling unplanned event types in this article.
Oops! Actually, it references the same article as mentioned in the prev comment (https://help.amplitude.com/hc/en-us/articles/360055495852-Configure-the-Schema-settings-to-handle-unexpected-data), so I think I can just remove this sentence in general

2023-11-17 14:09 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +Hence, if Google updates the data afterward - the import job will have to run again to get the updated numbers.
Right, a user clicks something -> Amplitude imports data from GA (so we have _click_, but no conversion yet) -> user then converts sometime later: we will see a conversion for this user in GA but not in Amplitude yet, because Amp imports this conversion data during the following sync

2023-11-17 14:09 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +You can learn more about handling unplanned event types in this article.
```suggestion
```

2023-11-17 14:21 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +### Import job ingests no data
I think a bulleted list would work well here. 
I am just not sure how to fix it without a suggestion raised on this (so I can accept a suggestion after you edit it)...

2023-11-17 14:22 UTC, zheniasemenina reviewed
Semi-final v.

2023-11-20 17:06 UTC, markzegarelli commented on docs/data/sources/google-ads.md
> +- When a conversion occurs days after the initial click
```suggestion

- When a conversion occurs days after the initial click
```

2023-11-20 17:42 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +### Import job ingests no data
done

2023-11-21 13:47 UTC, zheniasemenina commented on docs/data/sources/google-ads.md
> +Hence, if Google updates the data afterward - the import job will have to run again to get the updated numbers.
```suggestion
Hence, if Google updates the data afterward - the import job needs to run again to get the updated numbers.
```

2023-11-21 18:12 UTC, markzegarelli approved these changes

2023-11-21 20:04 UTC, merged