Create batch-cohort.md
amplitude/amplitude-dev-center pull request #84
Opened 2023-11-20 08:05 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-21 18:29 UTC, markzegarelli requested changes

2023-11-21 18:29 UTC, markzegarelli commented on docs/data/destinations/batch-cohort.md
> +To sync your first cohort, follow these steps:
```suggestion
To sync your first cohort:
```

2023-11-21 18:29 UTC, markzegarelli commented on docs/data/destinations/batch-cohort.md
> +Once the Cohort is synched to Batch, you should see it appear in the “Audiences” tab of the dashboard. You can then use it in a Push or In-App campaign by selecting it in the targeting section of the
```suggestion
When the Cohort is syncs to Batch, it appears in the “Audiences” tab of the dashboard. Select it in the targeting section of the campaign editor to use it in a Push or In-App campaign. This is useful if you want to include or exclude a segment of users from your campaign.
```

2023-11-21 18:29 UTC, markzegarelli commented on docs/data/destinations/batch-cohort.md
> +1. **Targeted Campaigns:** By syncing specific user cohorts from Amplitude, which segments users based on their behavior or attributes, to Batch, companies can create highly targeted push  or In-App
```suggestion
- **Targeted Campaigns:** When you sync specific user cohorts from Amplitude to Batch, you can target those users more directly in push or In-App campaigns. For example, target a cohort of users who have abandoned their shopping carts with a notification that offers a discount to encourage completion of the purchase.
```

2023-11-21 18:29 UTC, markzegarelli commented on docs/data/destinations/batch-cohort.md
> +2. **User Retention:** Cohorts of users who have not engaged with the app or website for a set period can be identified in Amplitude and synced to Batch. These users can then be re-engaged with perso
```suggestion
- **User Retention:** Identify cohorts of users who haven't engaged with the app or website for a set period in Amplitude and sync them to Batch. Re-engage these users with personalized content or updates relevant to their previous interactions, aiming to bring them back to the app or website.
```

2023-11-21 18:29 UTC, markzegarelli commented on docs/data/destinations/batch-cohort.md
> +3. **Product Feedback and Updates:** For users who have engaged with certain features of an app or service (a cohort identified in Amplitude), syncing this information to Batch would allow for sendin
```suggestion
- **Product Feedback and Updates:** For users who engage with certain features of an app or service (a cohort identified in Amplitude), syncing this information to Batch allows for sending specific notifications about updates, improvements, or requests for feedback on those features, ensuring that you reach the most relevant users.
```

2023-11-22 09:02 UTC, Brandoncharleskhoo1 commented on docs/data/destinations/batch-cohort.md
> +3. Click **Add another destination**.
![Screenshot 2023-11-22 at 1 01 44 AM](https://github.com/amplitude/amplitude-dev-center/assets/76189397/a4d1e71e-aec9-4c70-b328-2ea055dde42f)

Yeah basically once you click on a destination tile, it brings up this modal "Add another destination" for those integrations without an overview side panel.

2023-11-28 22:58 UTC, merged