Create refiner-cohort.md
amplitude/amplitude-dev-center pull request #87
Opened 2023-11-20 09:44 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-27 22:44 UTC, markzegarelli requested changes

2023-11-27 22:44 UTC, markzegarelli commented on docs/data/destinations/refiner-cohort.md
> +3. **Churn Prevention:** Spot potential churn risk cohorts in Amplitude, send them to Refiner and collect feedback. Proactively address user concerns to prevent churn and enhance overall customer sat
```suggestion
3. **Churn Prevention:** Spot potential churn risk cohorts in Amplitude, send them to Refiner and collect feedback. Proactively address user concerns to prevent churn and enhance customer satisfaction and retention strategies.
```

2024-01-26 00:44 UTC, Brandoncharleskhoo1 commented
@markzegarelli looks like i've addressed and committed your suggestions. Not sure what else needs to be changed.

2024-01-26 00:50 UTC, markzegarelli approved these changes

2024-01-26 00:50 UTC, merged