Create nami.md
amplitude/amplitude-dev-center pull request #88
Opened 2023-11-20 10:19 UTC by Brandoncharleskhoo1

# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

2023-11-27 22:48 UTC, markzegarelli requested changes

2023-11-27 22:48 UTC, markzegarelli commented on docs/data/sources/nami.md
> +- Before setting up this integration, please make sure that you are identifying your users in Nami using the same User_Ids that you also use in Amplitude. using the same User_Ids in both solutions. I
```suggestion
- Make sure that you indentify users in Nami using the same user identifier you use in Amplitude. If the user IDs don’t match, Amplitude can't match and merge survey response data with product use data of the same user.
```

2023-11-27 22:48 UTC, markzegarelli commented on docs/data/sources/nami.md
> +## Use Cases
```suggestion
## Use cases
```

2023-11-27 22:48 UTC, markzegarelli commented on docs/data/sources/nami.md
> +1. **In-App Monetization Optimization:** Nami empowers mobile app businesses to fine-tune their in-app monetization strategies. With Nami's user-friendly no-code paywall design tools, businesses can
@Brandoncharleskhoo1 We need to trim these down, it sounds like it's just marketing copy from Nami. Did this come from them or did you write it?

2023-11-28 19:07 UTC, Brandoncharleskhoo1 commented on docs/data/sources/nami.md
> +1. **In-App Monetization Optimization:** Nami empowers mobile app businesses to fine-tune their in-app monetization strategies. With Nami's user-friendly no-code paywall design tools, businesses can
Sure thing. We can trip them down. I can get them to review the marketing copy now.

2023-11-28 22:52 UTC, merged